### ISSUE TITLE
Missing ApiRegistryProviderModule when invoking ant target with Enunciate v2

### ISSUE THREAD

**Issue by Deraga** [stoicflame/enunciate#105]
Hi, 

I'm getting the following error when trying to invoke enunciate v2 using ant. 

Caused by: java.lang.ClassNotFoundException: com.webcohesion.enunciate.module.ApiRegistryProviderModule
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1388)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1337)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1089)

I'm using enunciate-core built from the latest commit & from the fix for issue #100
Thanks.

**Comment by stoicflame** [comment]
As of [Milestone 2](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.2), the "jax-rs-jackson" example now includes an Ant `build.xml` that works for me when I run "ant enunciate".
