### ISSUE TITLE
2.0.0-M2 com.webcohesion.enunciate.EnunciateException: There are no data types, services, or resources to document.

### ISSUE THREAD

**Issue by Deraga** [stoicflame/enunciate#109]
Hi,

I'm trying to invoke enunciate 2.0.0-M2 via ant. 
While i can execute the jax-rs-jackson example with no problem, I am getting the following exception with my own project. 

I've done some digging/debugging and I'm sure the resource files are loaded into and processed by enunciate but I'm not sure why enunciate is not getting any results (no data types, services, resources). 

Any help or tips is welcome. Thanks in advance. 

```
java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: There are no data types, services, or resources to document.
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:609)
	at com.webcohesion.enunciate.EnunciateTask.execute(EnunciateTask.java:143)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: com.webcohesion.enunciate.EnunciateException: There are no data types, services, or resources to document.
	at org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.call(DocumentationDeploymentModule.java:341)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onCompleted(SubjectSubscriptionManager.java:232)
	at rx.subjects.ReplaySubject.onCompleted(ReplaySubject.java:404)
	at rx.Observable$35.onCompleted(Observable.java:7458)
	at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:81)
	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:101)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:81)
	... 20 more
```

**Comment by stoicflame** [comment]
Thanks for the report. I've assigned this issue to Milestone 3.

I'm probably going to need some visibility into the project. Is there any way you and put together a sample project that reproduces the problem?

**Comment by marstonstudio** [comment]
It's a pretty big closed source project, that would be a challenge. 

Is it possible to add additional logging that would show which annotated class triggered the exception? If you have a debugging version of enunciate i can check out from a branch and use that to do test runs on the project to turn up more diagnostic info.

**Comment by stoicflame** [comment]
if you set `debug="true"` in the `<enunciate>` task, and run ant with "ant -d" there should be some information printed that might be useful.

**Comment by Deraga** [comment]
Hi,

I was using a configuration file that I used a while back with enunciate 1.29 which may be causing this issue.

By not using any configuration file (pointing configFile to some non-existing file like in the jax-rs-jackson example), I was able to get to the point with the same exception reported by #107 and #110 .

Anyway, below is the configuration file that I'm using.  Because I only need the documentation generation feature, i disabled other modules. Thanks for the help. 

<?xml version="1.0"?>
<enunciate label="g2sky" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0-SNAPSHOT.xsd">
	<webapp doCompile="false" doLibCopy="false">
	</webapp>
	<modules>
		<docs title="${sys.name} ${svcName} ${webtype} Rest API Documentation"
			copyright="oforsky.com" includeExampleJson="true" includeExampleXml="true"
			disableRestMountpoint="false" forceExampleJson="true" />
		<java-json-client disabled="true" />
		<java-xml-client disabled="true" />
		<jackson disabled="true" />
		<jackson1 disabled="true" />
		<jaxrs disabled="true" />
		<jaxws disabled="true" />
		<xml disabled="true" />
	</modules>
</enunciate>

**Comment by stoicflame** [comment]
The problem, in this case, is that you've disabled the "jaxrs" module (which processes the rest endpoints), the "jaxws" module (which processes the soap endpoints), the "jackson" module (which processes the json data model for Jackson 2, and the "jackson1" module (which processes the json data model for Jackson 1).

So after disabling all those, the docs module doesn't have anything to process (i.e. "no data types, services, or resources to document").
