### ISSUE TITLE
Syntax error in generated swagger.json

### ISSUE THREAD

**Issue by uniqueid001** [stoicflame/enunciate#121]
Using 2.0.0-M.3:

    Processing template jar:file:/tmp/enunciate-2.0.0-M.3/lib/enunciate-swagger-2.0.0-M.3.jar!/com/webcohesion/enunciate/modules/swagger/swagger.fmt.
    Error processing /tmp/redweb/build/enunciate-build/docs/ui/swagger.json.

    BUILD FAILED
    /tmp/redweb/build-docs.xml:89: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
     at [Source: java.io.FileReader@7dbed72; line: 5909, column: 14]
            at com.sun.tools.javac.main.Main.compile(Main.java:553)
            at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
            at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
            at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:650)
            at com.webcohesion.enunciate.EnunciateTask.execute(EnunciateTask.java:154)
            at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)

I checked the generated _swagger.json_ file and found that the `"default"` attribute is missing the comma separating it from the `"type"` attribute:

    "produces" : [ "application/json" ],
    "parameters" : [
      {
        "name" : "id",
        "in" : "formData",
        "default" : "-1"
        "type" : "string",
        "description" : "The requested report schedule to remove from the system."
      }

**Comment by uniqueid001** [comment]
Duplicate of #119.  (sorry - I didn't find it when I looked before submitting this)
