### ISSUE TITLE
Template bug? null or missing property.name

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#123]
I'm trying to run enunciate 2.0.0-M.3 on one of our projects, but it fails with (full exception at bottom):

```
==> property.name  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at l
ine 912, column 17]
```

I don't know if it is something in our source that causes it to break. This is the first project I try to process with an enunciate 2 build.

I'm hoping to get HTML documentation for the REST APIs in the code.

This is my config file:

```
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0-M.3.xsd">
  <api-classes>
    <include pattern="dk.jyskebank.service.**"/>
  </api-classes>

  <modules>
    <jaxrs groupBy="path"/>
    <docs title="foo" />

    <c disabled="true" />
    <c-xml-client disabled="true" />
    <csharp-xml-client disabled="true" />
    <jackson disabled="true" />
    <jackson1 disabled="true" />
    <java-json-client disabled="true" />
    <java-xml-client disabled="true" />
    <jaxws disabled="true" />
    <obj-c disabled="true" />
    <obj-c-xml-client disabled="true" />
    <php disabled="true" />
    <php-json-client disabled="true" />
    <php-xml-client disabled="true" />
    <ruby-json-client disabled="true" />
    <swagger disabled="true"/>		 	
  </modules>
</enunciate>
```

Let me know if you need me to provide anything else.

Thanks,
Jesper

```
[enunciate] SEVERE: Error executing FreeMarker template
[enunciate] FreeMarker template error:
[enunciate] The following has evaluated to null or missing:
[enunciate] ==> property.name  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/codehaus/enunciate/modules/docs/do
cs.fmt" at line 912, column 17]
[enunciate]
[enunciate] ----
[enunciate] Tip: It's the step after the last dot that caused this error, not those before it.
[enunciate] ----
[enunciate] Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!m
yDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, u
se parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[enunciate] ----
[enunciate]
[enunciate] ----
[enunciate] FTL stack trace ("~" means nesting-related):
[enunciate]     - Failed at: ${property.name}  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/codehaus/enunciate
/modules/docs/docs.fmt" in macro "processDataType" at line 912, column 15]
[enunciate]     ~ Reached through: #nested  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/codehaus/enunciate/mo
dules/docs/docs.fmt" in macro "boilerplate" at line 119, column 9]
[enunciate]     ~ Reached through: @boilerplate title=(title + ": " + ty...  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M
.3.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processDataType" at line 842, column 5]
[enunciate]     - Reached through: @file name=(type.slug + ".html")  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/
org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processDataType" at line 841, column 3]
[enunciate]     - Reached through: @processDataType type=type  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/co
dehaus/enunciate/modules/docs/docs.fmt" in macro "processDataSyntax" at line 826, column 13]
[enunciate]     ~ Reached through: #nested  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/codehaus/enunciate/mo
dules/docs/docs.fmt" in macro "boilerplate" at line 119, column 9]
[enunciate]     ~ Reached through: @boilerplate title=(title + ": " + sy...  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M
.3.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processDataSyntax" at line 807, column 5]
[enunciate]     - Reached through: @file name=(syntax.slug + ".html")  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar
!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processDataSyntax" at line 806, column 3]
[enunciate]     - Reached through: @processDataSyntax syntax=syntax  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/
org/codehaus/enunciate/modules/docs/docs.fmt" at line 261, column 9]
[enunciate]     ~ Reached through: #nested  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/codehaus/enunciate/mo
dules/docs/docs.fmt" in macro "boilerplate" at line 119, column 9]
[enunciate]     ~ Reached through: @boilerplate pagenav=pagenav  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/
codehaus/enunciate/modules/docs/docs.fmt" at line 170, column 3]
[enunciate]     - Reached through: @file name=indexPageName  [in template "jar:file:/d:/Downloads/enunciate-2.0.0-M.3/lib/enunciate-docs-2.0.0-M.3.jar!/org/code
haus/enunciate/modules/docs/docs.fmt" at line 159, column 1]
[enunciate] ----
[enunciate]
[enunciate] Java stack trace (for programmers):
[enunciate] ----
[enunciate] freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
[enunciate]     at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:116)
[enunciate]     at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:346)
[enunciate]     at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
[enunciate]     at freemarker.core.DollarVariable.accept(DollarVariable.java:40)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
[enunciate]     at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
[enunciate]     at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
[enunciate]     at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
[enunciate]     at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
[enunciate]     at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Macro$Context.runMacro(Macro.java:178)
[enunciate]     at freemarker.core.Environment.invoke(Environment.java:700)
[enunciate]     at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
[enunciate]     at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:377)
[enunciate]     at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Macro$Context.runMacro(Macro.java:178)
[enunciate]     at freemarker.core.Environment.invoke(Environment.java:700)
[enunciate]     at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
[enunciate]     at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
[enunciate]     at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
[enunciate]     at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
[enunciate]     at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
[enunciate]     at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
[enunciate]     at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
[enunciate]     at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
[enunciate]     at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
[enunciate]     at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Macro$Context.runMacro(Macro.java:178)
[enunciate]     at freemarker.core.Environment.invoke(Environment.java:700)
[enunciate]     at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
[enunciate]     at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:377)
[enunciate]     at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Macro$Context.runMacro(Macro.java:178)
[enunciate]     at freemarker.core.Environment.invoke(Environment.java:700)
[enunciate]     at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
[enunciate]     at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
[enunciate]     at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
[enunciate]     at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
[enunciate]     at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
[enunciate]     at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Macro$Context.runMacro(Macro.java:178)
[enunciate]     at freemarker.core.Environment.invoke(Environment.java:700)
[enunciate]     at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
[enunciate]     at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:377)
[enunciate]     at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.MixedContent.accept(MixedContent.java:62)
[enunciate]     at freemarker.core.Environment.visit(Environment.java:312)
[enunciate]     at freemarker.core.Environment.process(Environment.java:290)
[enunciate]     at freemarker.template.Template.process(Template.java:312)
[enunciate]     at org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.processTemplate(DocumentationDeploymentModule.java:349)
[enunciate]     at org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.call(DocumentationDeploymentModule.java:302)
[enunciate]     at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
[enunciate]     at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
[enunciate]     at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
[enunciate]     at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
[enunciate]     at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
[enunciate]     at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
[enunciate]     at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
[enunciate]     at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
[enunciate]     at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
[enunciate]     at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
[enunciate]     at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
[enunciate]     at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
[enunciate]     at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onCompleted(SubjectSubscriptionManager.java:232)
[enunciate]     at rx.subjects.ReplaySubject.onCompleted(ReplaySubject.java:404)
[enunciate]     at rx.Observable$35.onCompleted(Observable.java:7458)
[enunciate]     at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:81)
[enunciate]     at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
[enunciate]     at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
[enunciate]     at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
[enunciate]     at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
[enunciate]     at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
[enunciate]     at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
[enunciate]     at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
[enunciate]     at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
[enunciate]     at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
[enunciate]     at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
[enunciate]     at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
[enunciate]     at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
[enunciate]     at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
[enunciate]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[enunciate]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[enunciate]     at java.lang.Thread.run(Unknown Source)
[enunciate]
```

**Comment by stoicflame** [comment]
Bug. Thanks for the report.

I'm actually really surprised I didn't catch this case in the tests...

**Comment by stoicflame** [comment]
fixed at 287a7b4

**Comment by jskovjyskebankdk** [comment]
Thanks!

I've tried pulling the v2 to build it myself. Unfortunately, it fails for me:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project enunciate-javac-support: Compilation fail
ure: Compilation failure:
[ERROR] /C:/udvikler/ws/mars-test.git/enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedElement.java:[33,8] com
.webcohesion.enunciate.javac.decorations.element.DecoratedElement is not abstract and does not override abstract method <A>getAnnotationsByType(java.lang.Class<
A>) in javax.lang.model.AnnotatedConstruct
[ERROR] /C:/udvikler/ws/mars-test.git/enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedTypeParameterElement.ja
va:[31,8] com.webcohesion.enunciate.javac.decorations.element.DecoratedTypeParameterElement is not abstract and does not override abstract method <A>getAnnotati
onsByType(java.lang.Class<A>) in javax.lang.model.AnnotatedConstruct
[ERROR] /C:/udvikler/ws/mars-test.git/enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedTypeMirror.java:[27,8] com
.webcohesion.enunciate.javac.decorations.type.DecoratedTypeMirror is not abstract and does not override abstract method <A>getAnnotationsByType(java.lang.Class<
A>) in javax.lang.model.AnnotatedConstruct
...
```

I'm using java 8u60 and maven 3.3.3.

**Comment by stoicflame** [comment]
Yes, JDK 8 added some new methods to those interfaces. Enunciate is being built with JDK 7, with compatibility for JDK 6.

**Comment by stoicflame** [comment]
Fix was included in [Milestone 4](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.4). Thanks for the report, and please report any new issues.
