### ISSUE TITLE
enunciate struggles with non-jars in the dependency list

### ISSUE THREAD

**Issue by storysj** [stoicflame/enunciate#124]
I was trying to update the "wannabecool" example to v2.0.0-M.1 and java 8, and ran into issues because the javax.ws.rs.* classes were no longer packaged with java, but required a jersey dependency. I grabbed a set of jersey dependencies from another project, (accidentally including the jersey-bom:pom), and upon running `mvn clean install` I ran into:

```
[WARNING] could not create Dir using commons_vfs2 from url file:/Users/sstory/.m2/repository/org/glassfish/jersey/jersey-bom/2.20/jersey-bom-2.20.pom. skipping.
java.lang.NoClassDefFoundError: org/apache/commons/vfs2/VFS
	at org.reflections.vfs.Vfs$DefaultUrlTypes$7.matches(Vfs.java:281)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections$1.run(Reflections.java:199)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs2.VFS
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 10 more
```

just removing this dependency:

```
			<dependency>
				<groupId>org.glassfish.jersey</groupId>
				<artifactId>jersey-bom</artifactId>
				<version>${jersey.version}</version>
				<type>pom</type>
			</dependency>
```

resolved the error.

I tried with a few other non-default `<type>`s, and got the same `NoClassDefFoundError`

**Comment by stoicflame** [comment]
Great! Thanks for the report. Fixed at 71f7520.

**Comment by stoicflame** [comment]
Fix was included in [Milestone 4](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.4). Thanks for the report, and please report any new issues.

**Comment by storysj** [comment]
awesome! Thanks for the update, I'll try it out.
