### ISSUE TITLE
2.0.0-RC.1 Cannot resolve class with fully qualified package name

### ISSUE THREAD

**Issue by scoquelin** [stoicflame/enunciate#166]
Since we have two objects with the same name (unfortunately...) in the same class (`com/myproject/user/model/Company.java`), we had to define one of them using the fully qualified package name such as : 

`public final com.myproject.billing.model.Address billingAddress;`

while the other one is defined as : 

`public final Address address`

but here is the output I get from enunciate : 

````
[WARNING] [ENUNCIATE] [javac] [ERROR] ZipFileIndexFileObject[/home/seb/.m2/repository/com/myproject/myproject-model/0.0.1-SNAPSHOT/myproject-model-0.0.1-SNAPSHOT-sources.jar(com/myproject/user/model/Company.java)]:35:53 /home/seb/.m2/repository/com/myproject/myproject-model/0.0.1-SNAPSHOT/myproject-model-0.0.1-SNAPSHOT-sources.jar(com/myproject/user/model/Company.java):35: error: cannot access com.myproject.billing.model.Address
    public final com.myproject.billing.model.Address billingAddress;
                                                    ^
  bad source file: /home/seb/.m2/repository/com/myproject/myproject-model/0.0.1-SNAPSHOT/myproject-model-0.0.1-SNAPSHOT-sources.jar(com/myproject/billing/model/Address.java)
    file does not contain class com.myproject.billing.model.Address
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.582 s
[INFO] Finished at: 2015-09-25T15:29:45-04:00
[INFO] Final Memory: 71M/865M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-RC.1:docs (default-cli) on project myproject: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-RC.1:docs failed: Enunciate compile failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-RC.1:docs (default-cli) on project myproject: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-RC.1:docs failed: Enunciate compile failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-RC.1:docs failed: Enunciate compile failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: com.webcohesion.enunciate.EnunciateException: Enunciate compile failed.
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:681)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:368)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
````

and I can confirm that the "missing" class is actually part of the corresponding source package.

**Comment by stoicflame** [comment]
I've got bad news for you. This is a bug in the Java compiler; there's nothing I can do about it. This is the same issue as #117, so I'm going to close this as a duplicate and you can track the progress over there.

The only workaround I can offer you is to exclude that source jar from the source path, like this:

```xml
<plugin>
  <groupId>com.webcohesion.enunciate</groupId>
  <artifactId>enunciate-maven-plugin</artifactId>
  <version>${enunciate.version}</version>
  <executions>
    <execution>
      <id>assemble</id>
      <goals>
        <goal>assemble</goal>
      </goals>
      <configuration>
        <sourcepathExcludes>
          <exclude>
            <groupId>com.myproject</groupId>
            <artifactId>myproject-model</artifactId>
          </exclude>
        </sourcepathExcludes>
      </configuration>
    </execution>
  </executions>
</plugin>
```

However, that will have the unfortunate side-effect of making all the javadoc comments unavailable to Enunciate to include in your generated documentation.

**Comment by scoquelin** [comment]
Ok... Didn't see this coming ;-) Anyway, thanks @stoicflame !
