### ISSUE TITLE
Can't run via Java invocation

### ISSUE THREAD

**Issue by chibi03** [stoicflame/enunciate#183]
Hi!
When I try to run Enunciate from my Class using the class `com.webcohesion.enunciate.Enunciate` I keep getting the following error (in the case of feeding it `.java` files): 

```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/C:/workspace/my/dir/structure/MyJavaFile.java]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.Reflections.scan(Reflections.java:214)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at com.webcohesion.enunciate.Enunciate.loadApiReflections(Enunciate.java:755)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:547)
	at core.EnunciateTrigger.run(EnunciateTrigger.java:62)
	at core.EnunciateTrigger.main(EnunciateTrigger.java:126)
Caused by: java.util.concurrent.ExecutionException: org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/C:/workspace/my/dir/structure/MyJavaFile.java]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	... 6 more
Caused by: org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/C:/workspace/my/dir/structure/MyJavaFile.java]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections$1.run(Reflections.java:199)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Alternatively I tried bundling up my bundle containing the API I'd like it to document as a `.jar` but while it runs then, it doesn't throw any errors but doesn't complete either:
Debug output stops at: 
`[ENUNCIATE] [javac] ` 
where "" is the compilerOutput variable.

(So what is Enunciate expecting as source/class files plain .java or .jars?)

Any help would be appreciated Thanks!

**Comment by chibi03** [comment]
I solved it by sticking with JARs and adding the `DocsModule` which I was missing.
