### ISSUE TITLE
unable to generate anything with jax-rs?

### ISSUE THREAD

**Issue by avishaybennatan** [stoicflame/enunciate#202]
Hi , 
i was trying to integrate enunciate into existing jax-rs project ,
i am getting the following error:

```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.5:docs (default) on project flexicore: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.5:docs failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes. OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.5:docs (default) on project flexicore: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.5:docs failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.5:docs failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:650)
        at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:356)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
Caused by: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.
        at com.webcohesion.enunciate.modules.java_xml_client.JavaXMLClientModule.compileClientSources(JavaXMLClientModule.java:386)
        at com.webcohesion.enunciate.modules.java_xml_client.JavaXMLClientModule.call(JavaXMLClientModule.java:119)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
        at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
        at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
        at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
        at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
        at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
        at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
        at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
        at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:101)
        at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:81)
        ... 27 more
[DEBUG] [ENUNCIATE] C:\Users\Asaf\git\flexicore\target\enunciate\php-json-client\src is up-to-date because its oldest file, C:\Users\Asaf\git\flexicore\target\enunciate\php-json-client\src\flexicore.php, is younger than the youngest source file.
[INFO] [ENUNCIATE] Skipping PHP code generation because everything appears up-to-date.
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[DEBUG] [ENUNCIATE] C:\Users\Asaf\git\flexicore\target\enunciate\php-json-client\build is up-to-date because its oldest file, C:\Users\Asaf\git\flexicore\target\enunciate\php-json-client\build\flexicore-php.zip, is younger than the youngest source file.
[DEBUG] [ENUNCIATE] Processing template null.
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: com/webcohesion/enunciate/modules/php_json_client/PHPJSONClientModule$2
        at com.webcohesion.enunciate.modules.php_json_client.PHPJSONClientModule.processTemplate(PHPJSONClientModule.java:259)
        at com.webcohesion.enunciate.modules.php_json_client.PHPJSONClientModule.readResource(PHPJSONClientModule.java:326)
        at com.webcohesion.enunciate.modules.php_json_client.PHPJSONClientModule.call(PHPJSONClientModule.java:210)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
```

please help ?

POM:

```xml
<properties>
		<!-- Explicitly declaring the source encoding eliminates the following 
			message: -->
		<!-- [WARNING] Using platform encoding (UTF-8 actually) to copy filtered 
			resources, i.e. build is platform dependent! -->
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<!-- JBoss dependency versions -->
		<version.wildfly.maven.plugin>1.0.2.Final</version.wildfly.maven.plugin>
		<!-- Define the version of the JBoss BOMs we want to import to specify 
			tested stacks. -->
		<version.jboss.bom>8.2.1.Final</version.jboss.bom>

		<!-- other plugin versions -->
		<version.compiler.plugin>3.3</version.compiler.plugin>
		<version.surefire.plugin>2.16</version.surefire.plugin>
		<version.war.plugin>2.5</version.war.plugin>
		<version.eclipselink>2.6.1-RC1</version.eclipselink>

		<!-- maven-compiler-plugin -->
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.source>1.8</maven.compiler.source>
		<enunciate.version>2.0.0-M.5</enunciate.version>
	</properties>


	<dependencyManagement>
		<dependencies>

			<dependency>
				<groupId>org.wildfly.bom</groupId>
				<artifactId>jboss-javaee-7.0-with-tools</artifactId>
				<version>${version.jboss.bom}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>







			<dependency>
				<groupId>org.apache.httpcomponents</groupId>
				<artifactId>httpclient</artifactId>
				<version>4.4</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>

		<!-- First declare the APIs we depend on and need for compilation. All 
			of them are provided by JBoss WildFly -->

		<!-- Import the CDI API, we use provided scope as the API is included in 
			JBoss WildFly -->
		<dependency>
			<groupId>javax.enterprise</groupId>
			<artifactId>cdi-api</artifactId>
			<scope>provided</scope>
		</dependency>


		<!-- Import the Common Annotations API (JSR-250), we use provided scope 
			as the API is included in JBoss WildFly -->
		<dependency>
			<groupId>org.jboss.spec.javax.annotation</groupId>
			<artifactId>jboss-annotations-api_1.2_spec</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-multipart-provider</artifactId>
			<version>3.0.10.Final</version>
			<scope>provided</scope>
		</dependency>
		<!-- Import the JAX-RS API, we use provided scope as the API is included 
			in JBoss WildFly -->
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>jaxrs-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.reflections</groupId>
			<artifactId>reflections</artifactId>
			<version>0.9.9-RC1</version>
		</dependency>




		<!-- Import the EJB API, we use provided scope as the API is included in 
			JBoss WildFly -->
		<dependency>
			<groupId>org.jboss.spec.javax.ejb</groupId>
			<artifactId>jboss-ejb-api_3.2_spec</artifactId>
			<scope>provided</scope>
		</dependency>


		<!-- JSR-303 (Bean Validation) Implementation -->
		<!-- Provides portable constraints such as @Email -->
		<!-- Hibernate Validator is shipped in JBoss WildFly -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>5.1.3.Final</version>
			<scope>provided</scope>

			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>



		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>eclipselink</artifactId>
			<version>2.6.1-RC1</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
			<version>2.6.1-RC1</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.0</version>
		</dependency>


		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>org.eclipse.persistence.jpa.modelgen</artifactId>
			<version>2.4.2</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.wildfly</groupId>
			<artifactId>jipijapa-eclipselink</artifactId>
			<version>10.0.0.Beta1</version>
			<scope>provided</scope>
		</dependency>


		<!-- Needed for running tests (you may also use TestNG) -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- Optional, but highly recommended -->
		<!-- Arquillian allows you to test enterprise code such as EJBs and Transactional(JTA) 
			JPA from JUnit/TestNG -->
		<dependency>
			<groupId>org.jboss.arquillian.junit</groupId>
			<artifactId>arquillian-junit-container</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.jboss.arquillian.protocol</groupId>
			<artifactId>arquillian-protocol-servlet</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.10</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.spec.javax.batch</groupId>
			<artifactId>jboss-batch-api_1.0_spec</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bsc.maven</groupId>
			<artifactId>maven-processor-plugin</artifactId>
			<version>3.1.0-beta1</version>
		</dependency>
		<!-- <dependency> <groupId>com.flexicore</groupId> <artifactId>plugin.externals</artifactId> 
			<version>0.0.1-SNAPSHOT</version> <scope>compile</scope> </dependency> -->


		<!-- <dependency> -->
		<!-- <groupId>com.fasterxml.jackson.core</groupId> -->
		<!-- <artifactId>jackson-annotations</artifactId> -->
		<!-- <version>2.5.4</version> -->
		<!-- </dependency> -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.5.4</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.5.4</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.jaxrs</groupId>
			<artifactId>jackson-jaxrs-json-provider</artifactId>
			<version>2.6.2</version>
		</dependency>


		<dependency>
			<groupId>javax.enterprise.concurrent</groupId>
			<artifactId>javax.enterprise.concurrent-api</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
		</dependency>
		<dependency>
			<groupId>net.lingala.zip4j</groupId>
			<artifactId>zip4j</artifactId>
			<version>1.3.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
			<version>2.6.1</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.xnio</groupId>
			<artifactId>xnio-nio</artifactId>
			<version>3.3.2.Final</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.sasl</groupId>
			<artifactId>jboss-sasl</artifactId>
			<version>1.0.5.Final</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.remoting</groupId>
			<artifactId>jboss-remoting</artifactId>
			<version>4.0.14.Final</version>
		</dependency>

		<dependency>
			<groupId>com.github.nociar</groupId>
			<artifactId>jpa-cloner</artifactId>
			<version>1.0.3</version>
		</dependency>

		<dependency>
			<groupId>javax.jms</groupId>
			<artifactId>javax.jms-api</artifactId>
			<version>2.0.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.4-1204-jdbc42</version>
		</dependency>





	</dependencies>


	<build>
		<!-- Maven will append the version to the finalName (which is the name 
			given to the generated war, and hence the context root) -->
		<finalName>${project.artifactId}</finalName>
		<plugins>

			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<version>${version.war.plugin}</version>
				<configuration>
					<!-- Java EE 7 doesn't require web.xml, Maven needs to catch up! -->
					<failOnMissingWebXml>false</failOnMissingWebXml>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.bsc.maven</groupId>
				<artifactId>maven-processor-plugin</artifactId>
				<version>3.1.0-beta1</version>
				<executions>
					<execution>
						<id>eclipselink-jpa-metamodel</id>
						<goals>
							<goal>process</goal>
						</goals>
						<phase>generate-sources</phase>
						<configuration>
							<processors>
								<processor>org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor</processor>
							</processors>
							<outputDirectory>${project.build.directory}/generated-sources/meta-model</outputDirectory>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.eclipse.persistence</groupId>
						<artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
						<version>${version.eclipselink}</version>
					</dependency>



				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<compilerArgument>-proc:none</compilerArgument>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>2.4.1</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<minimizeJar>true</minimizeJar>
							<createDependencyReducedPom>true</createDependencyReducedPom>
							<dependencyReducedPomLocation>
								${java.io.tmpdir}/dependency-reduced-pom.xml
							</dependencyReducedPomLocation>
							<relocations>
								<relocation>
									<pattern>com.acme.coyote</pattern>
									<shadedPattern>hidden.coyote</shadedPattern>
								</relocation>
							</relocations>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>com.webcohesion.enunciate</groupId>
				<artifactId>enunciate-maven-plugin</artifactId>
				<version>${enunciate.version}</version>
				<configuration>
							
							<source>${maven.compiler.source}</source>
							<target>${maven.compiler.target}</target>
							<compilerArgument>-proc:none</compilerArgument>
							 <docsDir>${project.build.directory}/docs</docsDir>
						</configuration>
				<executions>
					<execution>
						<goals>
							<goal>docs</goal>
						</goals>
						
					</execution>
				</executions>
			</plugin>






		</plugins>
	</build>



</project>
```

**Comment by stoicflame** [comment]
So what source file is it trying to compile and why is the compile failing? You'll probably need to include the Javac output, too.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)

**Comment by avishaybennatan** [comment]
hmm but the exception says somthing about : 
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: com/webcohesion/enunciate/modules/php_json_client/PHPJSONClientModule$ExtensionDepthComparator


i dont need all these modules just from jax-rs to http 


also im getting these warnings:

warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release


even though i'm using java 1.8

**Comment by avishaybennatan** [comment]
ok here is the build error while running enunciate :+1: [INFO] --- enunciate-maven-plugin:2.1.1:docs (default-cli) @ flexicore ---
[WARNING] [ENUNCIATE] METHOD jobProperties of JobInformation: The C client doesn't have a built-in way of serializing a Map. Use @XmlJavaTypeAdapter to supply your own adapter for the Map.
[WARNING] [ENUNCIATE] METHOD requirments of JobInformation: The C client doesn't have a built-in way of serializing a Map. Use @XmlJavaTypeAdapter to supply your own adapter for the Map.
[WARNING] [ENUNCIATE] Web service API makes use of elements that cannot be handled by the C XML client. C XML client will not be generated.
[WARNING] [ENUNCIATE] METHOD jobProperties of JobInformation: The C# client doesn't have a built-in way of serializing a Map. Use @XmlJavaTypeAdapter to supply your own adapter for the Map.
[WARNING] [ENUNCIATE] METHOD requirments of JobInformation: The C# client doesn't have a built-in way of serializing a Map. Use @XmlJavaTypeAdapter to supply your own adapter for the Map.
[WARNING] [ENUNCIATE] METHOD result of Result: C# can't handle properties/fields that are of the same name as their containing class. Either rename the property/field, or use the @com.webcohesion.enunciate.metadata.ClientName annotation to rename the property/field on the client-side.
[WARNING] [ENUNCIATE] Web service API makes use of elements that cannot be handled by the C# XML client. C# XML client will not be generated.
[INFO] [ENUNCIATE] Skipping generation of GWT JSON Overlay as everything appears up-to-date...
[INFO] [ENUNCIATE] Skipping creation of the GWT overlay source jar as everything appears up-to-date...
[INFO] [ENUNCIATE] Skipping generation of Java client sources as everything appears up-to-date...
[INFO] [ENUNCIATE] Skipping compilation of Java JSON client classes as everything appears up-to-date...
[INFO] [ENUNCIATE] Skipping creation of Java client jar as everything appears up-to-date...
[INFO] [ENUNCIATE] Skipping creation of the Java client source jar as everything appears up-to-date...
[INFO] [ENUNCIATE] Skipping generation of Java client sources as everything appears up-to-date...
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
C:\Users\Asaf\git\flexicore\target\enunciate\java-xml-client\src\java\io\Serializable.java:15: error: interface expected here
public abstract class Serializable implements java.io.Serializable {
                                                     ^
C:\Users\Asaf\git\flexicore\target\enunciate\java-xml-client\src\java\io\Serializable.java:15: error: cyclic inheritance involving Serializable
public abstract class Serializable implements java.io.Serializable {
                ^
C:\Users\Asaf\git\flexicore\target\enunciate\java-xml-client\src\java\io\Serializable.java:11: error: annotation type not applicable to this kind of declaration
@javax.xml.bind.annotation.XmlType (
^
3 errors
4 warnings


 i guess that's because of: warning: [options] source value 1.5 is obsolete and will be removed in a future release
 but i'm using 1.8...

**Comment by stoicflame** [comment]
Okay, so somewhere Enunciate is picking up `java.io.Serializable` as if it were part of your API. Are you returning `java.io.Serializable` from a JAX-RS method? Is it a property type for a data object? Is it a parameter to a method?

Where/how are you using `Serializable`?

**Comment by avishaybennatan** [comment]
I am returning an object that has a field of seralizable (because that field can be anything ) , I'll try removing this field , just to be clear , its ok to return a class Implementing seralizable right ?

**Comment by avishaybennatan** [comment]
hmm it seems it is a bit problematic changing the field type from serializable ,
are you sure thats the problem ?
the field is with @jsonIgnore and the returned type from jax-rs is not serializable,
also the error:
public abstract class Serializable implements java.io.Serializable

isn't related to my code ( obviously i have not declared any class called serializable)

**Comment by stoicflame** [comment]
What happens if you annotate with field with @XmlTransient as well as @JsonIgnore.

What happens if you disabled JAXB processing entirely?

```
<enunciate>
  <modules>
    <jaxb disabled="true"/>
```

**Comment by stoicflame** [comment]
Try disabling jaxws, too:

```xml
<enunciate>
  <modules>
    <jaxb disabled="true"/>
    <jaxws disabled="true"/>
```

**Comment by avishaybennatan** [comment]
build is now successful but  the output doesnt contain classes with REST,
(guess because we have disabled jaxb and jaxws)

**Comment by stoicflame** [comment]
JAX-WS is SOAP. JAXB is XML. JAX-RS is REST. You haven't disabled JAX-RS, so there must be another reason REST classes aren't showing up. What classes are annotated with @Path? Are they included?

**Comment by Maskime** [comment]
Just for the sake of completeness, I had a smiliar issue and I realised that it was because I used the ```datatype-detection="aggressive"``` with the ```jax[b|rs|ws]``` modules (because I'm fairly new to this...) I removed it and did not have the error anymore.

**Comment by stoicflame** [comment]
Closing this issue due to lack of activity. I'd be happy to re-open as needed.
