### ISSUE TITLE
Annotations help: @Label @Typehint and Javadoc

### ISSUE THREAD

**Issue by chibi03** [stoicflame/enunciate#205]
Hi,
thanks for the new release.
I was looking at the new annotation @Label, where should it be added, just at the class definition? Does the class still need any JAXB annotations to be detected?

Do I need to enable something specific for the JavaDoc annotations i.e. @throws to show up?

Finally keep getting the following error when trying to use @TypeHint:
````
java.lang.RuntimeException: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.Class com.webcohesion.enunciate.metadata.rs.TypeHint.value() (Found data of type java.lang.Class<?>)
	at com.sun.tools.javac.main.Main.compile(Main.java:469)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:656)
	at core.EnunciateTrigger.run(EnunciateTrigger.java:98)
	at core.Main.main(Main.java:31)
Caused by: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.Class com.webcohesion.enunciate.metadata.rs.TypeHint.value() (Found data of type java.lang.Class<?>)
	at com.sun.tools.javac.model.AnnotationProxyMaker$ValueVisitor$1AnnotationTypeMismatchExceptionProxy.generateException(AnnotationProxyMaker.java:264)
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:83)
	at com.sun.proxy.$Proxy9.value(Unknown Source)
	at com.webcohesion.enunciate.util.TypeHintUtils.getTypeHint(TypeHintUtils.java:23)
	at com.webcohesion.enunciate.modules.jaxrs.model.ResourceMethod.<init>(ResourceMethod.java:161)
	at com.webcohesion.enunciate.modules.jaxrs.model.Resource.getResourceMethods(Resource.java:166)
	at com.webcohesion.enunciate.modules.jaxrs.model.Resource.<init>(Resource.java:88)
	at com.webcohesion.enunciate.modules.jaxrs.model.RootResource.<init>(RootResource.java:36)
	at com.webcohesion.enunciate.modules.jaxrs.JaxrsModule.call(JaxrsModule.java:96)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:101)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:81)
	... 15 more
````

When debugging I also found getAnnotation(TypeHint.class) was returning:
`@com.webcohesion.enunciate.metadata.rs.TypeHint(qualifiedName=##NONE, value=<error>)`
Although I set it to `@TypeHint(value=MyClass.class)` and MyClass.class is defined as XmlRootElement. 
Any help would be very much appreciated.

**Comment by stoicflame** [comment]
> I was looking at the new annotation @Label, where should it be added, just at the class definition?

Yes. I've updated the [Enunciate-Specific Annotations](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations) document. "Applied to a resource class, a data type, a web fault or a web service. Used to customize the label that is used for the element in the generated documentation."

> Does the class still need any JAXB annotations to be detected?

Not if it's a JSON data type.

> Do I need to enable something specific for the JavaDoc annotations i.e. `@throws` to show up?

No, it should show up in your SOAP web services. JAX-RS has no concept of "throws", so Enunciate doesn't use that element when generated REST documentation. If you're trying to document the possible error codes and warnings, see the annotations described at [Enunciate-Specific Annotations](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations).

> Finally keep getting the following error when trying to use @TypeHint

Weird. Maybe you're depending on some code that has been compiled using an older Enunciate version. The JavaDoc for that annotation says:

> Thrown to indicate that a program has attempted to access an element of an annotation whose type has changed after the annotation was compiled (or serialized).

**Comment by chibi03** [comment]
Thanks, I got it to work!
Does @TypeHint actually also work for the RequestBody dataTypes?

**Comment by stoicflame** [comment]
>  Does @TypeHint actually also work for the RequestBody dataTypes?

Yes.

**Comment by chibi03** [comment]
How can I specify it for the RequestBody ? If I just add the annotation my method it just shows up at the ResponseBody. And is it possibly to hint multiple dataTypes?

**Comment by stoicflame** [comment]
> How can I specify it for the RequestBody ? 

By annotating the parameter.

> And is it possibly to hint multiple dataTypes?

Not yet. #177
