### ISSUE TITLE
Error managing @XmlElementRefs

### ISSUE THREAD

**Issue by fcav1973** [stoicflame/enunciate#494]
Hi,
I have an annotated JAXB class for which I need to generate documentation (I'm using 2.6.0 version).  Generation blocks with the arror above (it works using 1.28-RC2 version). After some test, it seems that the probem is in the response class of a method. Commenting _@XmlElementRefs_, generation goes on (blocking, anyway, on another point).

The offending class seems to be:

```
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public final class SearchPolicyResult {

    /** A collection of PolicyElements. */
    @XmlElementRefs({
            @XmlElementRef(type = com.primeur.a3server.pub.api.authz.xacml.v1.policy.PolicyType.class),
            @XmlElementRef(type = com.primeur.a3server.pub.api.authz.xacml.v2.policy.PolicyType.class),
            @XmlElementRef(type = com.primeur.a3server.pub.api.authz.xacml.v3.PolicyType.class),
            @XmlElementRef(type = com.primeur.a3server.pub.api.authz.xacml.v1.policy.PolicySetType.class),
            @XmlElementRef(type = com.primeur.a3server.pub.api.authz.xacml.v2.policy.PolicySetType.class),
            @XmlElementRef(type = com.primeur.a3server.pub.api.authz.xacml.v3.PolicySetType.class) })
    private List<PolicyElementIf> wrappedCollection;

    /**
     * Instantiates a new SearchPolicyResult.
     */
    protected SearchPolicyResult() {
    }

    /**
     * Instantiates a SearchPolicyResult.
     * 
     * @param param
     *            the list of PolicyElements to return.
     */
    public SearchPolicyResult(final List<PolicyElementIf> param) {
        this.wrappedCollection = param;
    }

    /**
     * Gets the list of PolicyElements to return.
     * 
     * @return the list of PolicyElements to return.
     */
    public List<PolicyElementIf> getWrappedCollection() {
        if (wrappedCollection == null) {
            return Collections.emptyList();
        }
        return wrappedCollection;
    }

}
```

```
[DEBUG] [ENUNCIATE] Writing *****/target/enunciate/docs/apidocs/resource_RestPolicyAdministrationPointServiceIf.html...
set 06, 2016 9:16:31 AM freemarker.log._JULLoggerFactory$JULLogger error
GRAVE: Error executing FreeMarker template
FreeMarker template error:
An error has occurred when reading existing sub-variable "responseBody"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jaxrs.api.impl.MethodExampleImpl wrapped into f.e.b.StringModel)


FTL stack trace ("~" means nesting-related):
    - Failed at: ${method.example.responseBody?xhtml}  [in template "jar:file:/****/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.6.0/enunciate-docs-2.6.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 758, column 1]
    ~ Reached through: #nested  [in template "jar:file:/****/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.6.0/enunciate-docs-2.6.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 141, column 9]
    ~ Reached through: @boilerplate title=(title + ": " + re...  [in template "jar:file:/****/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.6.0/enunciate-docs-2.6.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 512, column 5]
    - Reached through: @file name=(resourceGroup.slug + ".ht...  [in template "jar:file:/****/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.6.0/enunciate-docs-2.6.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 511, column 3]
    - Reached through: @processResourceGroup resourceGroup=r...  [in template "jar:file:/****/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.6.0/enunciate-docs-2.6.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 235, column 11]
    ~ Reached through: #nested  [in template "jar:file:/****/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.6.0/enunciate-docs-2.6.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 141, column 9]
    ~ Reached through: @boilerplate pagenav=pagenav  [in template "jar:file:/****/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.6.0/enunciate-docs-2.6.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 192, column 3]
    - Reached through: @file name=indexPageName  [in template "jar:file:/****/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.6.0/enunciate-docs-2.6.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 181, column 1]


Java stack trace (for programmers):

freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
    at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
    at freemarker.core.Dot._eval(Dot.java:40)
    at freemarker.core.Expression.eval(Expression.java:78)
    at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
    at freemarker.core.BuiltInForString._eval(BuiltInForString.java:26)
    at freemarker.core.Expression.eval(Expression.java:78)
    at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
    at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
    at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
    at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
    at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
    at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
    at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
    at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.Environment.invokeNestedContent(Environment.java:546)
    at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.Macro$Context.runMacro(Macro.java:184)
    at freemarker.core.Environment.invoke(Environment.java:701)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
    at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:78)
    at freemarker.core.Environment.visit(Environment.java:389)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.Macro$Context.runMacro(Macro.java:184)
    at freemarker.core.Environment.invoke(Environment.java:701)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
    at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
    at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
    at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
    at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
    at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
    at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.Environment.invokeNestedContent(Environment.java:546)
    at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.Macro$Context.runMacro(Macro.java:184)
    at freemarker.core.Environment.invoke(Environment.java:701)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
    at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:78)
    at freemarker.core.Environment.visit(Environment.java:389)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.MixedContent.accept(MixedContent.java:54)
    at freemarker.core.Environment.visit(Environment.java:324)
    at freemarker.core.Environment.process(Environment.java:302)
    at freemarker.template.Template.process(Template.java:325)
    at com.webcohesion.enunciate.modules.docs.DocsModule.processTemplate(DocsModule.java:376)
    at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:324)
    at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46)
    at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25)
    at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
    at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
    at rx.Subscriber.setProducer(Subscriber.java:209)
    at rx.Subscriber.setProducer(Subscriber.java:205)
    at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:111)
    at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:175)
    at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:141)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:648)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
    at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:82)
    at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
    at rx.Subscriber.setProducer(Subscriber.java:211)
    at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
    at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:8460)
    at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
    at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
    at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
    at rx.Observable.unsafeSubscribe(Observable.java:8460)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
    at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172)
    at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85)
    at rx.Subscriber.setProducer(Subscriber.java:211)
    at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62)
    at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:8553)
    at rx.Observable.subscribe(Observable.java:8520)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:433)
    at rx.observables.BlockingObservable.single(BlockingObservable.java:332)
    at com.webcohesion.enunciate.EnunciateAnnotationProcessor.process(EnunciateAnnotationProcessor.java:107)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    at com.sun.tools.javac.main.Main.compile(Main.java:439)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
    at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:673)
    at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:401)
    at com.webcohesion.enunciate.mojo.DocsBaseMojo.execute(DocsBaseMojo.java:96)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
    at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
    at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
    ... 184 more
Caused by: java.lang.IllegalArgumentException: A type definition must be supplied.
    at com.webcohesion.enunciate.modules.jaxb.model.types.XmlClassType.<init>(XmlClassType.java:33)
    at com.webcohesion.enunciate.modules.jaxb.model.ElementRef$DeclarationReferencedElement.getXmlType(ElementRef.java:460)
    at com.webcohesion.enunciate.modules.jaxb.model.ElementRef.getXmlType(ElementRef.java:259)
    at com.webcohesion.enunciate.modules.jaxb.api.impl.ExampleImpl.build(ExampleImpl.java:196)
    at com.webcohesion.enunciate.modules.jaxb.api.impl.ExampleImpl.getBody(ExampleImpl.java:81)
    at com.webcohesion.enunciate.modules.jaxrs.api.impl.MethodExampleImpl.getResponseBody(MethodExampleImpl.java:187)
    ... 190 more
```

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
This one is pretty ugly. I've been unable to reproduce it, and as much as I stare at the code I still can't figure out how it gets in this state.

At 6f45e8d, I added a more informative error message that will help track down the issue. You can build a snapshot version of Enunciate and try it out, or you can wait until 2.7 ships and try it out. Please update this thread with the new error message so we can continue to pursue the issue.

**Comment by stoicflame** [comment]
Still no word on this error.

I'll re-open if the reporter comments again.
