### ISSUE TITLE
Current master does not build

### ISSUE THREAD

**Issue by SpOOnman** [stoicflame/enunciate#504]
With master on 7d03d79 Ryan Heaton on 19.09.16 at 19:03 initial support for context-modifying modules project does not build on maven. Build was fine two commits ago at 63013c9 Ryan Heaton on 24.08.16 at 19:56 fix a missed loop condition breaking #456.

```
maven -DskipTests=true install

...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Enunciate - Parent ................................ SUCCESS [0.967s]
[INFO] Enunciate - Core Annotations ...................... SUCCESS [2.258s]
[INFO] Enunciate - Javac Support ......................... SUCCESS [1.767s]
[INFO] Enunciate - Core Build-time Support ............... SUCCESS [2.893s]
[INFO] Enunciate - Runtime Utilities ..................... SUCCESS [0.709s]
[INFO] Enunciate - JAXB XML Model Support ................ SUCCESS [1.484s]
[INFO] Enunciate - Jackson 2.x JSON Model Support ........ SUCCESS [1.021s]
[INFO] Enunciate - Jackson 1.x JSON Model Support ........ SUCCESS [0.778s]
[INFO] Enunciate - JAX-RS Model Support .................. SUCCESS [0.828s]
[INFO] Enunciate - JAX-WS Model Support .................. SUCCESS [0.725s]
[INFO] Enunciate - Spring Web Model Support .............. SUCCESS [0.929s]
[INFO] Enunciate - IDL Module ............................ SUCCESS [0.953s]
[INFO] Enunciate - Java XML Client Module ................ SUCCESS [6.110s]
[INFO] Enunciate - Java JSON Client Module ............... SUCCESS [4.665s]
[INFO] Enunciate - C# XML Client Module .................. SUCCESS [0.739s]
[INFO] Enunciate - C XML Client Module ................... SUCCESS [0.661s]
[INFO] Enunciate - Objective C XML Client Module ......... SUCCESS [0.767s]
[INFO] Enunciate - PHP XML Client Module ................. SUCCESS [0.619s]
[INFO] Enunciate - PHP JSON Client Module ................ SUCCESS [0.746s]
[INFO] Enunciate - Ruby JSON Client Module ............... SUCCESS [0.769s]
[INFO] Enunciate - JavaScript Client Module .............. SUCCESS [0.728s]
[INFO] Enunciate - GWT JSON Overlay Module ............... SUCCESS [3.592s]
[INFO] Enunciate - Swagger Module ........................ SUCCESS [0.915s]
[INFO] Enunciate - Docs Module ........................... SUCCESS [0.581s]
[INFO] Enunciate - Slim Maven Plugin ..................... SUCCESS [2.390s]
[INFO] Enunciate - Top ................................... SUCCESS [1.150s]
[INFO] Enunciate - Maven Plugin .......................... SUCCESS [3.062s]
[INFO] Enunciate - Simple Archetype ...................... SUCCESS [0.640s]
[INFO] Enunciate - Example Projects ...................... SUCCESS [0.218s]
[INFO] Enunciate - Full API With Edge Cases Example ...... SUCCESS [2.409s]
[INFO] Enunciate - Jackson 2 API Example ................. FAILURE [4.461s]
[INFO] Enunciate - Jersey Storage Example ................ SKIPPED
[INFO] Enunciate - Spring-Managed Jersey Storage Example . SKIPPED
[INFO] Enunciate - JBoss Full API Example ................ SKIPPED
[INFO] Enunciate - CXF Full API Example .................. SKIPPED
[INFO] Enunciate - Spring-Web Petclinic Example .......... SKIPPED
[INFO] Enunciate - Contract-First API Example ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.531s
[INFO] Finished at: Wed Sep 21 00:17:10 CEST 2016
[INFO] Final Memory: 124M/839M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.7.0-SNAPSHOT:assemble (assemble) on project enunciate-examples-jax-rs-jackson: Execution assemble of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.7.0-SNAPSHOT:assemble failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.7.0-SNAPSHOT:assemble (assemble) on project enunciate-examples-jax-rs-jackson: Execution assemble of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.7.0-SNAPSHOT:assemble failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution assemble of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.7.0-SNAPSHOT:assemble failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 25 more
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.contains(Hashtable.java:365)
	at java.util.Hashtable.containsValue(Hashtable.java:392)
	at com.webcohesion.enunciate.modules.jaxb.NamespacePropertiesArtifact.exportTo(NamespacePropertiesArtifact.java:84)
	at com.webcohesion.enunciate.mojo.AssembleBaseMojo.postProcess(AssembleBaseMojo.java:115)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:443)
	at com.webcohesion.enunciate.mojo.AssembleBaseMojo.execute(AssembleBaseMojo.java:101)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 26 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :enunciate-examples-jax-rs-jackson```

**Comment by SpOOnman** [comment]
I confirm that master builds on 087812a Ryan Heaton on 21.09.16 at 00:29 fixes #504: NPE in NamespacePropertiesArtifact. Thank you for quick support!
