### ISSUE TITLE
Error invoking Enunciate. java.lang.IllegalArgumentException: createBase64Binary(byte[]): parameter type must be a declared type. OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class

### ISSUE THREAD

**Issue by gvdwink** [stoicflame/enunciate#510]
Trying to use Enunciate (2.6.0) (using Maven) with our API's. I got the following failure:

from the code:

```java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }
```

and Build fails with:

```
Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.6.0:docs (default) on project telco-subscriber: Error invoking Enunciate. java.lang.IllegalArgumentException: createBase64Binary(byte[]): parameter type must be a declared type. OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.6.0:docs (default) on project telco-subscriber: Error invoking Enunciate.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error invoking Enunciate.
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:408)
	at com.webcohesion.enunciate.mojo.DocsBaseMojo.execute(DocsBaseMojo.java:96)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: createBase64Binary(byte[]): parameter type must be a declared type.
	at com.sun.tools.javac.main.Main.compile(Main.java:469)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:673)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:401)
	... 22 more
Caused by: java.lang.IllegalArgumentException: createBase64Binary(byte[]): parameter type must be a declared type.
	at com.webcohesion.enunciate.modules.jaxb.model.LocalElementDeclaration.<init>(LocalElementDeclaration.java:70)
	at com.webcohesion.enunciate.modules.jaxb.model.Registry.getLocalElementDeclarations(Registry.java:85)
	at com.webcohesion.enunciate.modules.jaxb.EnunciateJaxbContext.add(EnunciateJaxbContext.java:464)
	at com.webcohesion.enunciate.modules.jaxb.EnunciateJaxbContext.add(EnunciateJaxbContext.java:432)
	at com.webcohesion.enunciate.modules.jaxb.JaxbModule.addPotentialJaxbElement(JaxbModule.java:139)
	at com.webcohesion.enunciate.modules.jaxws.JaxwsModule.call(JaxwsModule.java:167)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.Subscriber.setProducer(Subscriber.java:209)
```

**Comment by stoicflame** [comment]
Okay, thanks for the report.

**Comment by masooh** [comment]
Is there a workaround for this bug?

I'm getting the same error for:
```java
@XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestValue")
public JAXBElement<byte[]> createDigestValue(byte[] value) {
    return new JAXBElement<byte[]>(_DigestValue_QNAME, byte[].class, null, ((byte[]) value));
}
```

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)

**Comment by gvdwink** [comment]
I can confirm bug has been solved.
