### ISSUE TITLE
Regexp pattern with digit-matcher lost one of two backslashes

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#537]
Using patterns with digit-matcher in 2.7.0 fails:

````
	@GET
	@Path("{konto}/indfrielseskurser")
	@Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
	public Response getIndfrielseskurser(@Pattern(regexp = "\\d{1,14}", message = "Kontonummer skal være 14 cifre (4 regnr, 10 kontonr") @PathParam("konto") String konto) {
		return Response.ok(refinanseringsService.getIndfrielsesKurser(new KontoId(konto))).build();
	}
````

Results in the following in swagger.json (notice the pattern lost its escaping backslash):

````
    "\/accounts/{konto}/indfrielseskurser" : {
      "get" : {
        "tags" : [ "Bolig" ],
        "summary" : "Hent refinanserings kurser for jyskebank bolig lån.",
        "description" : "Hent refinanserings kurser for jyskebank bolig lån\r\n\r\n<p>\r\n<img src=\"../../../images/samples.jpg\"/>\r\n<\/p>\r\n<table class=\"note\">\r\n<tr>\r\n<td>Kurser for et F3<\/td>\r\n<td><a target=\"_blank\" href=\"../../../rest/accounts/50110001447442/indfrielseskurser\"\\>accounts/50110001447442/indfrielseskurser<\/><\/td>\r\n<\/tr>\r\n<\/table>",
        "operationId" : "resource_Bolig_getIndfrielseskurser_GET",
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [
          {
            "name" : "konto",
            "in" : "path",
            "required" : true,
            "type" : "string",
            "pattern" : "\d{1,14}",
            "description" : ""
          }
        ],
        "responses" : {
          "200" : {
            "schema" : {
"description" : "",
"type" : "file"
            },
            "headers" : {
            },
            "examples" : {
            },
            "description" : "Success"
          }
        }
      }
    }
````

Which causes the enunciate process to fail with the exception (I cut the top, let me know if you want more):

````
Execution failed for task ':jb.it.jess.web:enunciate'.
> com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape 'd' (code 100)
 at [Source: java.io.FileReader@b6d1bc1; line: 58989, column: 28]
....

Caused by: com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape 'd' (code 100)
 at [Source: java.io.FileReader@b6d1bc1; line: 58989, column: 28]
        at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:333)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25)
        at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
        at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
        at rx.Subscriber.setProducer(Subscriber.java:209)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:111)
        at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:175)
        at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:141)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:648)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
        at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:82)
        at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
        at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:8460)
        at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
        at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
        at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
        at rx.Observable.unsafeSubscribe(Observable.java:8460)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
        at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172)
        at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62)
        at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:8553)
        at rx.Observable.subscribe(Observable.java:8520)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:433)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:332)
        at com.webcohesion.enunciate.EnunciateAnnotationProcessor.process(EnunciateAnnotationProcessor.java:116)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 80 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape 'd' (code 100)
 at [Source: java.io.FileReader@b6d1bc1; line: 58989, column: 28]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._handleUnrecognizedCharacterEscape(ParserMinimalBase.java:495)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._decodeEscaped(ReaderBasedJsonParser.java:2045)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:1610)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:1584)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:233)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:230)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:267)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:62)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2106)
        at com.webcohesion.enunciate.modules.swagger.SwaggerDeploymentModule$SwaggerInterfaceDescription.writeTo(SwaggerDeploymentModule.java:170)
        at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:300)
        ... 136 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:192)
        at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
        ... 133 more
````

**Comment by jayenashar** [comment]
I have the same issue in a `BeanParam`:

    @QueryParam("min_price")
    @Pattern(regexp = "|50|100|200|300|\\$400|500|600|700|800|900|1000|1100|1200|1300|1400|1500")
    private String        min_price;

gives a big stack trace.  i assume this is the relevant bit:

```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape '$' (code 36)
 at [Source: java.io.FileReader@129a5b9; line: 117, column: 44]
```

If I make it like this:

    @Pattern(regexp = "|50|100|200|300|\\\\$400|500|600|700|800|900|1000|1100|1200|1300|1400|1500")

then the enunciate page contains `regex: |50|100|200|300|\\$400|500|600|700|800|900|1000|1100|1200|1300|1400|1500` in the `Contraints` column.  The swagger json looks ok with `"pattern": "|50|100|200|300|\\$400|500|600|700|800|900|1000|1100|1200|1300|1400|1500",`

I think in this case, I want to specify the regex with `\\$400`, the enunciate to show `\$400` and the swagger.json to contain `\\$400`.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
