### ISSUE TITLE
Build error using 2.8.0

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#570]
First of all, thanks for the latest release!

I gave it a testdrive, but it dies during build with the exception below. It seems it's failing to
read the generated swagger.json file. Looking at the error position shows:

```json
            "roles" : {
            "minItems" : 1,
            "maxItems" : 2.147.483.647,
"description" : "The assigned roles for the account.",
"type" : "array",
"items" : {
  "$ref" : "#/definitions/json_Role"
}
            }
```

It seems failing at `maxItems`, parsing the dot in the max value. I checked it against an older `swagger.json` of 2.7.0 and there are not dots in that value. Any hints?

Thanks!

```java
[WARNING] [ENUNCIATE] Error processing E:\Coding\workspace\someproject\pg-web\pg-web-impl\target\docs\apidocs\ui\swagger.json.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Web ................................................ SUCCESS [  0.334 s]
[INFO] WebAPI ............................................. SUCCESS [  8.108 s]
[INFO] WebApp ............................................. FAILURE [  7.965 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.529 s
[INFO] Finished at: 2016-12-19T23:47:26+01:00
[INFO] Final Memory: 73M/612M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.8.0:docs (default) on project pg-web-impl: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('.' (code 46)): was expecting comma to separate OBJECT entries
[ERROR] at [Source: java.io.FileReader@3163d61e; line: 1545, column: 32]: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.8.0:docs (default) on project pg-web-impl: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('.' (code 46)): was expecting comma to separate OBJECT entries
 at [Source: java.io.FileReader@3163d61e; line: 1545, column: 32]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('.' (code 46)): was expecting comma to separate OBJECT entries
 at [Source: java.io.FileReader@3163d61e; line: 1545, column: 32]
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:406)
	at com.webcohesion.enunciate.mojo.DocsBaseMojo.execute(DocsBaseMojo.java:96)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('.' (code 46)): was expecting comma to separate OBJECT entries
 at [Source: java.io.FileReader@3163d61e; line: 1545, column: 32]
	at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:333)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.Subscriber.setProducer(Subscriber.java:209)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:111)
	at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:175)
	at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:141)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:648)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:82)
	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:8460)
	at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
	at rx.Observable.unsafeSubscribe(Observable.java:8460)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:8553)
	at rx.Observable.subscribe(Observable.java:8520)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:433)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:332)
	at com.webcohesion.enunciate.EnunciateAnnotationProcessor.process(EnunciateAnnotationProcessor.java:122)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:673)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:401)
	... 23 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('.' (code 46)): was expecting comma to separate OBJECT entries
 at [Source: java.io.FileReader@3163d61e; line: 1545, column: 32]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:1794)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:608)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:218)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2106)
	at com.webcohesion.enunciate.modules.swagger.SwaggerDeploymentModule$SwaggerInterfaceDescription.writeTo(SwaggerDeploymentModule.java:170)
	at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:300)
	... 83 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:192)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
	... 80 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pg-web-impl

```

**Comment by stoicflame** [comment]
Thanks for the report. It has to do with the way numbers get written in some locales. I'll fix it.

**Comment by vguna** [comment]
Thanks for looking into this!

**Comment by jskovjyskebankdk** [comment]
I had not noticed the 2.8.1 release. If I read the release contents correctly, this fix should be included, right?

Unfortunately I still see the problem (or one similar).

````
        "parameters" : [
          {
            "name" : "initiator",
            "in" : "path",
            "required" : true,
            "type" : "string",
            "maxLength" : 2.147.483.647,
            "minLength" : 1,
            "description" : "the user to search for."
          },
````

This is on a box with Danish locale.

**Comment by stoicflame** [comment]
That's weird.

@vguna, does 2.8.1 still work for you?

**Comment by vguna** [comment]
Just tried 2.8.1 and the build went through without any errors. My machine is Windows7, german locale. I didn't know that there was a fix release. Thanks Ryan!

**Comment by jskovjyskebankdk** [comment]
Hm, maybe it is because I tried to substitute the 2.8.0 jars with 2.8.1 manually.

@stoicflame could you make a 2.8.1 release of the gradle plugin, please? Maybe the plugin was actually using 2.8.0 even though I had 2.8.1 jars on the classpath.

**Comment by stoicflame** [comment]
Done.

**Comment by jskovjyskebankdk** [comment]
Hm, certainly a different behavior. Now applying the plugin alone causes problems.
I am unsure why, and do not have time to dig into it right now.
It works for vguna, so I trust it is just something local that breaks things for me.

I will revisit it in a while and let you know (in another issue) if it still causes problems for me.
Cheers!

**Comment by vguna** [comment]
Hm. Sorry to report this, but 2.8.1 throws the same error on my linux CI using jenkins:

```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.8.1:docs (default) on project pg-web-impl: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('0' (code 48)): was expecting double-quote to start field name
[ERROR] at [Source: java.io.FileReader@673f72a2; line: 3924, column: 28]: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[ERROR] -> [Help 1]
```

My windows machine works though. weird...

**Comment by stoicflame** [comment]
Probably deserves a separate issue, but I need some way to reproduce the problem.

My build environment is Linux.

**Comment by vguna** [comment]
Interesting :). I'll try to look into it today...

**Comment by vguna** [comment]
Hm. Funny thing is: on my linux machine there is LANG=en_US.UTF-8 set. The build breaks with it. If I simply set it to de_DE.UTF-8 the build works.

Did you make it work for only non-US environments now ;)?

locale -a returns:

```
C
C.UTF-8
de_DE
de_DE@euro
de_DE.iso88591
de_DE.iso885915@euro
de_DE.utf8
en_US
en_US.iso88591
en_US.iso885915
en_US.utf8
POSIX
```

So it has something todo with the locale. Anything else you want me to check?

**Comment by stoicflame** [comment]
I'm afraid I still just can't reproduce the issue. :-(

For me, the number gets correctly generated no matter what locale I use.

It smells like something with your environment. Are you certain you're not picking up version 2.8.0 somehow? If you build 2.9.0-SNAPSHOT, can you reproduce the problem?

**Comment by vguna** [comment]
Did some further testing. I double checked that I have no 2.8.0 lying around. Checked .m2 folder, and made sure, that only 2.8.1 exists there.

Then I also started a fresh virtual box with Ubuntu 16.04 on it and built enunciate 2.9.0-SNAPSHOT from master as described (not exactly, since some packages named differently now) with openjdk 7.

Then, I moved my sources there and switched enunciate version to 2.9.0-SNAPSHOT instead. Same behavior as on my CI linux box. Switched back to 2.8.1 with the same behavior. Also this time using openjdk instead of oracle jdk (like on my CI box).

Maybe _you_ have something configured, maybe during the bugfixing and debugging, that is now set to DE or something :)?

**Comment by vguna** [comment]
Hm. Digged deeper. I took a look at your fix for this at:

https://github.com/stoicflame/enunciate/commit/792a4d77b28f60e228dbcffb3811822ffc8609b1

I also spotted two additional places, where I guess the fix should be applied. Once for parameter and for header constraints. Your fix only was applied to properties.

Funny thing is: re-compiled enunciate with the additional fixes now works with my build no matter what I set for `LANG`. This is somehow weird, right :)?

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)

If you see any problems with this release, please open up new issues.

**Comment by niloc132** [comment]
Confirmed, this issue isn't fully fixed after updating to 2.9.0. Parameter `@DefaultValue("100") @QueryParam("maxcount") @Max(1000) Integer maxCount` is emitted in swagger.json as 

```
          {
            "name" : "maxcount",
            "in" : "query",
            "default" : "100",
            "type" : "integer",
            "maximum" : 1,000,
            "description" : ""
          },
```

**Comment by stoicflame** [comment]
I'm sorry guys; I didn't listen close enough to @vguna to let what he was trying to tell me sink in.

I think I finally fixed this at 0e2e59b, and cut a patch release 2.9.1 that you can use.

**Comment by niloc132** [comment]
Looking good from here, thanks for the quick response! Releases take time, we're glad 2.9.0 shipped when it was ready, and equally glad that you had the time to look into this so soon after shipping a new version.

**Comment by vguna** [comment]
No problem :). Thanks for fixing this so quickly!
