### ISSUE TITLE
NPE in JavaScriptClientModule

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#595]
```
java.lang.NullPointerException: null
	at com.webcohesion.enunciate.modules.javascript_client.JavaScriptClientModule.findExampleResourceMethod(JavaScriptClientModule.java:359) ~[na:na]
	at com.webcohesion.enunciate.modules.javascript_client.JavaScriptClientModule.readResource(JavaScriptClientModule.java:332) ~[na:na]
	at com.webcohesion.enunciate.modules.javascript_client.JavaScriptClientModule.call(JavaScriptClientModule.java:214) ~[na:na]
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46) ~[na:na]
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25) ~[na:na]
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80) ~[na:na]
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65) ~[na:na]
	at rx.Subscriber.setProducer(Subscriber.java:209) ~[na:na]
	at rx.Subscriber.setProducer(Subscriber.java:205) ~[na:na]
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:111) ~[na:na]
	at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:175) ~[na:na]
	at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:141) ~[na:na]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:648) ~[na:na]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560) ~[na:na]
```

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
