### ISSUE TITLE
Error after upgrading enunciate 2.7.1 -> 2.9.1

### ISSUE THREAD

**Issue by pstryq** [stoicflame/enunciate#639]
Hey, we tried in our project to upgrade enunciate according to the issue topic but error occurred.
Any ideas why is that happening? Same for 2.8.0 and 2.9.0.

```
[javac] [ERROR] null:-1:-1 error: cannot access org.springframework.osgi.context.BundleContextAware
[javac] error: cannot access org.springframework.osgi.context.BundleContextAware
[javac]   class file for org.springframework.osgi.context.BundleContextAware not found
[javac]   Consult the following stack trace for details.
[javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.springframework.osgi.context.BundleContextAware not found
[javac]   Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[javac]         at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
[javac]         at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:192)
[javac]         at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
[javac]         at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
[javac]         at rx.Subscriber.setProducer(Subscriber.java:209)
[javac]         at rx.Subscriber.setProducer(Subscriber.java:205)
[javac]         at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:111)
[javac]         at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:175)
[javac]         at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:141)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:648)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
[javac]         at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:82)
[javac]         at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[javac]         at rx.Subscriber.setProducer(Subscriber.java:211)
[javac]         at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[javac]         at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.Observable.unsafeSubscribe(Observable.java:8460)
[javac]         at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
[javac]         at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
[javac]         at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
[javac]         at rx.Observable.unsafeSubscribe(Observable.java:8460)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[javac]         at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[javac]         at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[javac]         at rx.Subscriber.setProducer(Subscriber.java:211)
[javac]         at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[javac]         at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.Observable.unsafeSubscribe(Observable.java:8460)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[javac]         at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[javac]         at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[javac]         at rx.Subscriber.setProducer(Subscriber.java:211)
[javac]         at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[javac]         at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.Observable.unsafeSubscribe(Observable.java:8460)
[javac]         at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
[javac]         at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
[javac]         at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
[javac]         at rx.Observable.unsafeSubscribe(Observable.java:8460)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[javac]         at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[javac]         at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172)
[javac]         at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85)
[javac]         at rx.Subscriber.setProducer(Subscriber.java:211)
[javac]         at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62)
[javac]         at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[javac]         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[javac]         at rx.Observable.subscribe(Observable.java:8553)
[javac]         at rx.Observable.subscribe(Observable.java:8520)
[javac]         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:433)
[javac]         at rx.observables.BlockingObservable.single(BlockingObservable.java:332)
[javac]         at com.webcohesion.enunciate.EnunciateAnnotationProcessor.process(EnunciateAnnotationProcessor.java:122)
[javac]         at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
[javac]         at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
[javac]         at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
[javac]         at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
[javac]         at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
[javac]         at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
[javac]         at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
[javac]         at com.sun.tools.javac.main.Main.compile(Main.java:523)
[javac]         at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[javac]         at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[javac]         at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:674)
[javac]         at com.webcohesion.enunciate.gradle.EnunciateTask.run(EnunciateTask.java:160)
[javac]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javac]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javac]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]         at java.lang.reflect.Method.invoke(Method.java:498)
[javac]         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
[javac]         at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
[javac]         at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
[javac]         at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
[javac]         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
[javac]         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
[javac]         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
[javac]         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
[javac]         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
[javac]         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
[javac]         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
[javac]         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
[javac]         at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
[javac]         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
[javac]         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
[javac]         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[javac]         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
[javac]         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
[javac]         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
[javac]         at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
[javac]         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
[javac]         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
[javac]         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
[javac]         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
[javac]         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
[javac]         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
[javac]         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
[javac]         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
[javac]         at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
[javac]         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
[javac]         at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
[javac]         at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
[javac]         at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
[javac]         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
[javac]         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
[javac]         at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:256)
[javac]         at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:253)
[javac]         at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
[javac]         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
[javac]         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
[javac]         at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:175)
[javac]         at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
[javac]         at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
[javac]         at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
[javac]         at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
[javac]         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[javac]         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
[javac]         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
[javac]         at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
[javac]         at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
[javac]         at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
[javac]         at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
[javac]         at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
[javac]         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[javac]         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[javac]         at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
[javac]         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[javac]         at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
[javac]         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[javac]         at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
[javac]         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[javac]         at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
[javac]         at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
[javac]         at org.gradle.util.Swapper.swap(Swapper.java:38)
[javac]         at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
[javac]         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[javac]         at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
[javac]         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[javac]         at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
[javac]         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[javac]         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[javac]         at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
[javac]         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[javac]         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[javac]         at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
[javac]         at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
[javac]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[javac]         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
[javac]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[javac]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[javac]         at java.lang.Thread.run(Thread.java:745)
:dgc-core-rest:enunciate FAILED
```

**Comment by stoicflame** [comment]
What version of spring are you using? 

What version of spring-osgi are you using?

**Comment by pstryq** [comment]
Spring 4.2.4. I am afraid we are not using spring-osgi. I tried to add some dependency for spring-osgi but that led to some compilation errors within our code which should not happen of course.

**Comment by stoicflame** [comment]
I just don't think I have enough information to know how to address the issue. It seems like there's some reference (perhaps transitive?) to `BundleContextAware` that needs to be resolved.

Can you provide any suggestions about how to reproduce the error?

**Comment by pstryq** [comment]
I think I have already checked all the subprojects and it seems that there is no trace of reference to spring-osgi (or anything similar).

**Comment by stoicflame** [comment]
Isn't the error about something referencing `BundleContextAware` and not finding spring-osgi on the classpath? Wouldn't you want to include spring-osgi?

You may want to try verbose logging (e.g. `mvn -X`) to find out what's being added and where it's being added.

**Comment by stoicflame** [comment]
I'm afraid I've got nothing more I can do on my end to debug the issue. At f1d51f0 I updated to the latest Spring (4.2.8) without issues.

If you'd like to provide me a way I can reproduce this on my end, I'd be happy to re-open this issue and help debug.
