### ISSUE TITLE
Issue with enunciate-jackson in 2.9.1: null:-1:-1 error: cannot access org.springframework.hateoas.ResourceSupport

### ISSUE THREAD

**Issue by tbfky** [stoicflame/enunciate#665]
Same error when using 2.8.1 but works with 2.7.0.

The reason for upgrading is to get support for springs composed annotations such as org.springframework.web.bind.annotation.GetMapping.

```
            <plugin>
                <groupId>com.webcohesion.enunciate</groupId>
                <artifactId>enunciate-slim-maven-plugin</artifactId>
                <version>${enunciate.version}</version>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>docs</goal>
                        </goals>
                        <configuration>
                            <configFile>${project.basedir}/enunciateconfig.xml</configFile>
                            <docsDir>${project.build.directory}/generated-resources/static/rest</docsDir>
                            <source>1.8</source>
                            <target>1.8</target>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-docs</artifactId>
                        <version>${enunciate.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-spring-web</artifactId>
                        <version>${enunciate.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-jackson</artifactId>
                        <version>${enunciate.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-swagger</artifactId>
                        <version>${enunciate.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

```
[WARNING] [ENUNCIATE] [javac] [ERROR] null:-1:-1 error: cannot access org.springframework.hateoas.ResourceSupport
[WARNING] [ENUNCIATE] [javac] error: cannot access org.springframework.hateoas.ResourceSupport
[WARNING] [ENUNCIATE] [javac]   class file for org.springframework.hateoas.ResourceSupport not found
[WARNING] [ENUNCIATE] [javac]   Consult the following stack trace for details.
[WARNING] [ENUNCIATE] [javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.springframework.hateoas.ResourceSupport not found
[WARNING] [ENUNCIATE] [javac]   Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[WARNING] [ENUNCIATE] [javac]   	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
[WARNING] [ENUNCIATE] [javac]   	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:192)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
[WARNING] [ENUNCIATE] [javac]   	at rx.Subscriber.setProducer(Subscriber.java:209)
[WARNING] [ENUNCIATE] [javac]   	at rx.Subscriber.setProducer(Subscriber.java:205)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:111)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:175)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:141)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:648)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:82)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]   	at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
[WARNING] [ENUNCIATE] [javac]   	at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]   	at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]   	at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
[WARNING] [ENUNCIATE] [javac]   	at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85)
[WARNING] [ENUNCIATE] [javac]   	at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]   	at rx.Observable.subscribe(Observable.java:8553)
[WARNING] [ENUNCIATE] [javac]   	at rx.Observable.subscribe(Observable.java:8520)
[WARNING] [ENUNCIATE] [javac]   	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:433)
[WARNING] [ENUNCIATE] [javac]   	at rx.observables.BlockingObservable.single(BlockingObservable.java:332)
[WARNING] [ENUNCIATE] [javac]   	at com.webcohesion.enunciate.EnunciateAnnotationProcessor.process(EnunciateAnnotationProcessor.java:122)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.main.Main.compile(Main.java:523)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[WARNING] [ENUNCIATE] [javac]   	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[WARNING] [ENUNCIATE] [javac]   	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:674)
[WARNING] [ENUNCIATE] [javac]   	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:401)
[WARNING] [ENUNCIATE] [javac]   	at com.webcohesion.enunciate.mojo.DocsBaseMojo.execute(DocsBaseMojo.java:96)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[WARNING] [ENUNCIATE] [javac]   	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[WARNING] [ENUNCIATE] [javac]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING] [ENUNCIATE] [javac]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[WARNING] [ENUNCIATE] [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[WARNING] [ENUNCIATE] [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
[WARNING] [ENUNCIATE] [javac]   	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[WARNING] [ENUNCIATE] [javac]   	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[WARNING] [ENUNCIATE] [javac]   	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[WARNING] [ENUNCIATE] [javac]   	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] [ENUNCIATE] [javac]   	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[WARNING] [ENUNCIATE] [javac]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING] [ENUNCIATE] [javac]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[WARNING] [ENUNCIATE] [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[WARNING] [ENUNCIATE] [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
[WARNING] [ENUNCIATE] [javac]   	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by stoicflame** [comment]
Looks like you pulled in a class that depends on `org.springframework.hateoas.ResourceSupport` to compile.

Try adding `spring-hateoas` jar to the classpath?

**Comment by stoicflame** [comment]
Bump. 

Anything to report here?

**Comment by stoicflame** [comment]
I'm going to close this for now. If I can get more info, I'm happy to reopen.
