### ISSUE TITLE
java.lang.NoSuchMethodException: No such accessible method: addClientPackageConversion() 

### ISSUE THREAD

**Issue by stokito** [stoicflame/enunciate#70]
I'm trying to upgrade maven-enunciate-plugin from 1.2.0 to 1.2.1 or latter and getting this error: 

```
[INFO] --- maven-enunciate-plugin:1.30.1:assemble (default) @ tain-commons-integration ---
Mar 31, 2015 6:23:44 PM org.apache.commons.digester.Digester endElement
SEVERE: End event threw exception
java.lang.NoSuchMethodException: No such accessible method: addClientPackageConversion() on object: org.codehaus.enunciate.modules.java_client.config.ClientPackageConversion
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:279)
	at org.apache.commons.digester.SetNextRule.end(SetNextRule.java:220)
	at org.apache.commons.digester.Rule.end(Rule.java:257)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1345)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:607)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1323)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2750)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:625)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:489)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:828)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:757)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:133)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1211)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:551)
	at org.apache.commons.digester.Digester.parse(Digester.java:1940)
	at org.codehaus.enunciate.config.EnunciateConfiguration.load(EnunciateConfiguration.java:893)
	at org.codehaus.enunciate.config.EnunciateConfiguration.load(EnunciateConfiguration.java:749)
	at org.codehaus.enunciate.config.EnunciateConfiguration.load(EnunciateConfiguration.java:740)
	at org.codehaus.enunciate.ConfigMojo.loadConfig(ConfigMojo.java:490)
	at org.codehaus.enunciate.ConfigMojo.execute(ConfigMojo.java:332)
	at org.codehaus.enunciate.AssembleMojo.execute(AssembleMojo.java:56)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -------------------------------------------------------------
```

Configuration in pom.xml looks like
```xml
   <plugin>
                <groupId>org.codehaus.enunciate</groupId>
                <artifactId>maven-enunciate-plugin</artifactId>
                <version>1.30.1</version>
                <extensions>true</extensions>
                <configuration>
                    <configFile>enunciate.xml</configFile>
                    <generateDir>${project.build.directory}/enunciate-generate</generateDir>
                    <compileDir>${project.build.directory}/enunciate-compile</compileDir>
                    <buildDir>${project.build.directory}/enunciate-build</buildDir>
                    <packageDir>${project.build.directory}/enunciate-package</packageDir>
                    <outputDir>${project.build.directory}</outputDir>
                    <artifacts>
                        <artifact>
                            <enunciateArtifactId>client.jdk15.library.binaries</enunciateArtifactId>
                            <artifactType>jar</artifactType>
                            <classifier>client</classifier>
                        </artifact>
                        <artifact>
                            <enunciateArtifactId>jaxws.client.library.binaries</enunciateArtifactId>
                            <artifactType>jar</artifactType>
                            <classifier>jaxws-client</classifier>
                        </artifact>
                        <artifact>
                            <enunciateArtifactId>docs</enunciateArtifactId>
                            <artifactType>zip</artifactType>
                            <classifier>docs</classifier>
                        </artifact>
                    </artifacts>
                    <exports>
                        <docs>${project.build.finalName}-docs.zip</docs>
                    </exports>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.enunciate</groupId>
                        <artifactId>enunciate-xfire</artifactId>
                        <version>1.20</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.enunciate</groupId>
                        <artifactId>enunciate-jaxws-client</artifactId>
                        <version>1.20fix01</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun</groupId>
                        <artifactId>tools</artifactId>
                        <version>1.6.0</version>
                        <scope>system</scope>
                        <systemPath>${java.home}/../lib/tools.jar</systemPath>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by stoicflame** [comment]
Hi.

This was a known issue in earlier versions of Enunciate. Have you tried updating to 1.30?

**Comment by stokito** [comment]
Yes, I tried latest v1.30.1 but exception still thrown. I have some additional details:

```
[ERROR] Failed to execute goal org.codehaus.enunciate:maven-enunciate-plugin:1.30.1:assemble (default) on project tain-commons-integration: Problem with enunciate config file integration\enunciate.xml: Error at line 27 char 102: No such accessible method: addClientPackageConversion() on object: org.codehaus.enunciate.modules.java_client.config.ClientPackageConversion -> [Help 1]
```

In the `enunciate.xml` at line 27 :

```xml
    <modules>
        <jaxws disabled="false"/>
        <jaxws-client disabled="false">
            <package-conversions>
                <convert from="xx.xxxx.commons.integration" to="xx.xxxx.commons.integration.client"/> //line 27
            </package-conversions>
        </jaxws-client>
    </modules>
```

**Comment by stoicflame** [comment]
I think your problem is in your pom.xml:

```xml
<dependency>
    <groupId>org.codehaus.enunciate</groupId>
    <artifactId>enunciate-xfire</artifactId>
    <version>1.20</version>
</dependency>
<dependency>
    <groupId>org.codehaus.enunciate</groupId>
    <artifactId>enunciate-jaxws-client</artifactId>
    <version>1.20fix01</version>
</dependency>
```

Those dependency versions need to be the same as the Enunciate version (1.30.1).
