### ISSUE TITLE
Support java generic intersection types

### ISSUE THREAD

**Issue by NielsDoucet** [stoicflame/enunciate#805]
When using generic intersection types, enunciate fails.

Consider the following generic type argument on a model:
`public class Model<STATUS extends Enum<STATUS> & StatusInterface>`
Where there are multiple enums implementing the StatusInterface interface.

Running enunciate generates the following exception
```
Caused by: javax.lang.model.type.UnknownTypeException: Unknown type: java.lang.Enum<STATUS>&com.example.StatusInterface
        at com.sun.tools.javac.code.Type$IntersectionClassType.accept(Type.java:1037)
        at com.webcohesion.enunciate.javac.decorations.TypeMirrorDecorator.decorate(TypeMirrorDecorator.java:56)
        at com.webcohesion.enunciate.javac.decorations.type.DecoratedTypeVariable.getUpperBound(DecoratedTypeVariable.java:43)
        at com.webcohesion.enunciate.modules.jackson.EnunciateJacksonContext$ReferencedJsonDefinitionVisitor.visitTypeVariable(EnunciateJacksonContext.java:674)
        at com.webcohesion.enunciate.modules.jackson.EnunciateJacksonContext$ReferencedJsonDefinitionVisitor.visitTypeVariable(EnunciateJacksonContext.java:613)
        at com.webcohesion.enunciate.javac.decorations.type.DecoratedTypeVariable.accept(DecoratedTypeVariable.java:57)
        at com.webcohesion.enunciate.modules.jackson.EnunciateJacksonContext.addReferencedTypeDefinitions(EnunciateJacksonContext.java:485)
        at com.webcohesion.enunciate.modules.jackson.EnunciateJacksonContext.addReferencedTypeDefinitions(EnunciateJacksonContext.java:470)
        at com.webcohesion.enunciate.modules.jackson.EnunciateJacksonContext.add(EnunciateJacksonContext.java:400)
        at com.webcohesion.enunciate.modules.jackson.EnunciateJacksonContext$ReferencedJsonDefinitionVisitor.visitDeclared(EnunciateJacksonContext.java:646)
        at com.webcohesion.enunciate.modules.jackson.EnunciateJacksonContext$ReferencedJsonDefinitionVisitor.visitDeclared(EnunciateJacksonContext.java:613)
        at com.webcohesion.enunciate.javac.decorations.type.DecoratedDeclaredType.accept(DecoratedDeclaredType.java:84)
        at com.webcohesion.enunciate.modules.jackson.EnunciateJacksonContext.addReferencedTypeDefinitions(EnunciateJacksonContext.java:485)
        at com.webcohesion.enunciate.modules.jackson.JacksonModule.addDataTypeDefinitions(JacksonModule.java:172)
        at com.webcohesion.enunciate.modules.jaxrs.JaxrsModule.addReferencedDataTypeDefinitions(JaxrsModule.java:246)
        at com.webcohesion.enunciate.modules.jaxrs.JaxrsModule.call(JaxrsModule.java:148)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25)
```

I believe this is caused by the fact that the TypeMirrorDecorator extends from javax.lang.model.util.SimpleTypeVisitor6 (https://github.com/stoicflame/enunciate/blob/master/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/TypeMirrorDecorator.java#L31).
SimpleTypeVisitor6 implement visitIntersection as follows:

```
public R visitIntersection(IntersectionType t, P p) {
    return visitUnknown(t, p);
}

public R visitUnknown(TypeMirror t, P p) {
    throw new UnknownTypeException(t, p);
}
```

Is there a chance that TypeMirrorDecorator could be implemented in a more generic fashion, allowing for the TypeVisitor applicable for the java version the project is built in to be used instead?

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).

**Comment by NielsDoucet** [comment]
Great, thanks :)
Will give this a go real soon.
