### ISSUE TITLE
The generated swagger json for multiple operations residing under the same method/path is not compliant to Swagger 2.0

### ISSUE THREAD

**Issue by xeagle2** [stoicflame/enunciate#809]
Hi,

I would like if you can help with the following issue, when the generated swagger.json is not compliant to Swagger / OpenAPI 2.0 spec when there are multiple operations are under the same method / path, but distinguished by produced media types. Please see more details at https://github.com/swagger-api/swagger-ui/issues/4114

Thank you,

**Comment by stoicflame** [comment]
Are you reporting that Enunciate is generating incorrect `swagger.json`?

If so, can you please provide details about the interface methods that cause this behavior?

**Comment by xeagle2** [comment]
Hi @stoicflame 

The annotated methods are below

```
@Path("results/{key}")
@GET
@Produces({
  MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN
})
public AsyncResult getResult(@PathParam("key") String key) {
  return new AsyncResultImpl(key);
}
```

```
@Path("results/{key}")
@GET
@Produces({
  MediaType.APPLICATION_OCTET_STREAM
})
public StreamingOutput getResultBinary(@PathParam("key") String key) {
  return new AsyncResultImpl(key).getBinary();
}
```
Below is the snippet of generated swagger.json

```
"\/0/results/{key}" : {
      "get" : {
        "tags" : [ "..." ],
        "summary" : "Get a queued result.",
        "description" : "Get a queued result.",
        "operationId" : "getResult",
        "produces" : [ "application/xml", "application/json", "text/plain" ],
        "parameters" : [
          {
            "name" : "key",
            "in" : "path",
            "required" : true,
            "type" : "string",
            "description" : "the key"
          }
        ],
        "responses" : {
          "200" : {
            "schema" : {
              "$ref" : "#/definitions/json_AsyncResult"
            },
            "example" : {
              "key" : "...",
              "progressText" : "...",
              "releaseTime" : 12345,
              "completionTime" : 12345,
              "exception" : {
                "errorKey" : "...",
                "stackTrace" : "...",
                "statusCode" : 12345,
                "error" : "...",
                "message" : "..."
              },
              "operationResult" : {
                "displayInfo" : { },
                "data" : { },
                "dataType" : "..."
              },
              "progress" : 12345.0,
              "completed" : true,
              "startTime" : 12345
            },
            "description" : "the result"
          }
        }
      }
    ,
      "get" : {
        "tags" : [ "..." ],
        "summary" : "Get a queued result as binary.",
        "description" : "Get a queued result as binary.",
        "operationId" : "getResultBinary",
        "produces" : [ "application/octet-stream" ],
        "parameters" : [
          {
            "name" : "key",
            "in" : "path",
            "required" : true,
            "type" : "string",
            "description" : "the key"
          }
        ],
        "responses" : {
          "200" : {
            "description" : "the result"
          }
        }
      }
    }
```
The snippet violates the swagger json schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json and JSON https://tools.ietf.org/html/rfc7159#section-4

> The names within an object SHOULD be unique.

**Comment by derekm** [comment]
I'm seeing the same thing. Enunciate needs to upgrade to Swagger 2.0, which is in its release candidate stage.

**Comment by stoicflame** [comment]
You may be interested in [Jyskebank/enunciate-openapi](https://github.com/Jyskebank/enunciate-openapi)

**Comment by derekm** [comment]
@stoicflame -- Are you associated with this particular Enunciate module? It'd be nice to get it published out to Maven Central. I'd love to help get Maven instructions for this module, also. Seems like something that will be upstreamed eventually...

**Comment by stoicflame** [comment]
I'm not. It was created and published by @jskovjyskebankdk. I'll let him comment on Maven instructions and upstreaming.

**Comment by jskovjyskebankdk** [comment]
I have started the certification process with Sonatype.

But I cannot commit to a time frame. The project was released as-is on request.
I do want to get it on maven central though - so it is just a question of time.

**Comment by jskovjyskebankdk** [comment]
The enunciate-openapi module is now on Maven Central.

Not terribly relevant for this issue, but since I was summoned here, I figured I could mention it :)

**Comment by xeagle2** [comment]
@stoicflame 

I tried to generate the docs using openapi module (maven):

Using
```
<plugin>
        <groupId>com.webcohesion.enunciate</groupId>
        <artifactId>enunciate-maven-plugin</artifactId>
        <version>2.10.1</version>
        <executions>
          <execution>
            <goals>
              <goal>docs</goal>
            </goals>
            <configuration>
              <configFile>${project.basedir}/src/main/enunciate/enunciate.xml</configFile>
              <disableSourcepath>true</disableSourcepath>
              <encoding>UTF-8</encoding>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>dk.jyskebank.tooling.enunciate</groupId>
            <artifactId>enunciate-openapi</artifactId>
            <version>1.0.4</version>
          </dependency>
        </dependencies>
</plugin>
```

enunciate.xml

```
<modules>
    <!--<swagger basePath="..."/>-->
    <openapi disabled="false" />
</modules>
```

And getting the following errors

```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.10.1:docs (default) on project rest: Error invoking Enunciate.: java.lang.NullPointerException: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.10.1:docs (default) on project rest: Error invoking Enunciate.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error invoking Enunciate.
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:408)
	at com.webcohesion.enunciate.mojo.DocsBaseMojo.execute(DocsBaseMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:674)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:401)
	... 23 more
Caused by: java.lang.NullPointerException
	at com.webcohesion.enunciate.modules.spring_web.SpringWebApiRegistry.getResourceApis(SpringWebApiRegistry.java:33)
	at com.webcohesion.enunciate.api.AggregatedApiRegistry.getResourceApis(AggregatedApiRegistry.java:44)
	at dk.jyskebank.tools.enunciate.modules.openapi.OpenApiModule.call(OpenApiModule.java:141)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
```

Is there any idea what could be the root cause of the issue ?
