### ISSUE TITLE
ResourceMethodSignature is broken when use array type class as output

### ISSUE THREAD

**Issue by nfalco79** [stoicflame/enunciate#823]
We have a class annotated @ResourceMethodSignature to describe input parameters.
```
@ResourceMethodSignature(queryParams = { @QueryParam("l"), @QueryParam("o"), @QueryParam("by"), @QueryParam("filter"), @QueryParam("displayName"),
            @QueryParam("email") }, output = ContactDTO[].class)
@GET
@Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
@NonNull
public List<ContactDTO> getAll(@Context @NonNull IQueryParam queryParam)
```

Here there are two issues.
I would not use output attribute of ResourceMethodSignature  annotation because I expect enunciate uses the return type in the signature. But this does not happen instead if output is not specified the return type is missing in the documentation.

Since the output attribute is therefore mandatory I have some troubles in case of parametric types like List, Collection, Set and so on where the parametric type is lost. As workaround I had try to use `ContactDTO[].class` (for example in JSON array or list are the same) but if fails to generate the documentation (it does not create anything) without any message in the most recent version 2.10.1, in previous version 2.8.1 I got the following exception:
```
[ERROR] Error invoking Enunciate.
org.apache.maven.plugin.MojoExecutionException: getAll(com.acme.IQueryParam): Illegal output type (must be a declared type): com.acme.dto.ContactDTO[]
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:406)
	at com.webcohesion.enunciate.mojo.DocsBaseMojo.canGenerateReport(DocsBaseMojo.java:172)
	at org.apache.maven.reporting.exec.MavenReportExecution.canGenerateReport(MavenReportExecution.java:89)
	at org.apache.maven.plugins.site.render.AbstractSiteRenderingMojo.getReports(AbstractSiteRenderingMojo.java:267)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:115)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.webcohesion.enunciate.EnunciateException: getAll(com.acme.IQueryParam): Illegal output type (must be a declared type): com.acme.dto.ContactDTO[]
	at com.webcohesion.enunciate.modules.jaxrs.model.ResourceMethod.loadOutputPayload(ResourceMethod.java:595)
```

I would prefer that the build fails with an error instead of having to notice it only after and after months that the documentation has not been generated

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
