### ISSUE TITLE
Support for OpenAPI 3

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#856]
Update to Swagger 2.

**Comment by xeagle2** [comment]
@stoicflame 

I tried to generate the docs using openapi module (maven):

Using
```
<plugin>
        <groupId>com.webcohesion.enunciate</groupId>
        <artifactId>enunciate-maven-plugin</artifactId>
        <version>2.10.1</version>
        <executions>
          <execution>
            <goals>
              <goal>docs</goal>
            </goals>
            <configuration>
              <configFile>${project.basedir}/src/main/enunciate/enunciate.xml</configFile>
              <disableSourcepath>true</disableSourcepath>
              <encoding>UTF-8</encoding>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>dk.jyskebank.tooling.enunciate</groupId>
            <artifactId>enunciate-openapi</artifactId>
            <version>1.0.4</version>
          </dependency>
        </dependencies>
</plugin>
```

enunciate.xml

```
<modules>
    <!--<swagger basePath="..."/>-->
    <openapi disabled="false" />
</modules>
```

And getting the following errors

```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.10.1:docs (default) on project rest: Error invoking Enunciate.: java.lang.NullPointerException: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.10.1:docs (default) on project rest: Error invoking Enunciate.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error invoking Enunciate.
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:408)
	at com.webcohesion.enunciate.mojo.DocsBaseMojo.execute(DocsBaseMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:674)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:401)
	... 23 more
Caused by: java.lang.NullPointerException
	at com.webcohesion.enunciate.modules.spring_web.SpringWebApiRegistry.getResourceApis(SpringWebApiRegistry.java:33)
	at com.webcohesion.enunciate.api.AggregatedApiRegistry.getResourceApis(AggregatedApiRegistry.java:44)
	at dk.jyskebank.tools.enunciate.modules.openapi.OpenApiModule.call(OpenApiModule.java:141)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
```

Is there any idea what could be the root cause of the issue ?

**Comment by panchenko** [comment]
The root cause is it's not unknown yet how OpenApiModule should be configured to work in maven.

**Comment by stoicflame** [comment]
Thanks @panchenko. 

Indeed, I'd suggest you open an issue over at [Jyskebank/enunciate-openapi](https://github.com/Jyskebank/enunciate-openapi), or wait until this issue gets resolved.

**Comment by xeagle2** [comment]
got it, thanks :)

**Comment by bkalas** [comment]
I had exactly same proplem.
Solved by disabling spring-web module
`<?xml version="1.0" encoding="UTF-8"?>
<enunciate>
    <modules>
        <openapi disabled="false" />
        <spring-web disabled="true" />
    </modules>
</enunciate>`

**Comment by xeagle2** [comment]
Thanks for the note, I didn't use spring-web module in my case, interesting :)

**Comment by AlexandrSokolov** [comment]
Guys, it would be great if you start supporting OpenApi 3 natively. The current enunciate-openapi does not supprt the last version of enunciate. More and more our clients ask our services to provide OpenApi 3  support to simplify the client generation and usage of services.

**Comment by amberream** [comment]
Yes, OpenAPI is up to version 3.1.  Looks like the Swagger docs are still version 2.0.  Any update on when this might be implemented?

**Comment by stoicflame** [comment]
Updated to OpenAPI 3.0 in Enunciate 2.15.0.
