### ISSUE TITLE
StackOverflow on Map<>

### ISSUE THREAD

**Issue by JKam123** [stoicflame/enunciate#882]
Hello,

I am having a problem here. When compiling my project i get StackOverflows. Using the IntelliJ debugger I traced it to this bit of code in my project

```
@XmlJavaTypeAdapter(TypeAXMLAdapter.class)
public enum TypeA implements TypeB{
```
where TypeAXMLAdapter is this:

```
public class TypeAXMLAdapter extends XmlAdapter<TypeA, TypeB> {
	@Override
	public TypeB unmarshal(TypeA v) throws Exception {
		return v;
	}

	@Override
	public TypeA marshal(TypeB v) throws Exception {
		return v.getTypeA();
	}

}
```
Enunciate config:
`<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0-M.4.xsd">

    <title>Title</title>

    <copyright>MyComp</copyright>

    <modules>
        

        <docs docsSubdir="docs"
              css="style.css"
              faviconUri="icon.png"
              indexPageName="index.html"
              freemarkerTemplate="docs.fmt">
        </docs>
        <c-xml-client disabled="true"/>
        <csharp-xml-client disabled="true"/>
        <java-xml-client disabled="true"/>
        <gwt-json-overlay disabled="true"/>
        <obj-c-client disabled="true"/>
        <obj-c-xml-client disabled="true"/>
        <php-json-client disabled="true"/>
        <php-xml-client disabled="true"/>
        <java-json-client disabled="true"/>
        <ruby-json-client disabled="true"/>
    </modules>

    <api-classes>
        <include pattern="mypackage.docs.**"/>
        <exclude pattern="**.helper.*"/>
        <exclude pattern="**.api.*"/>
        <exclude pattern="mypackage.TypeA" />
    </api-classes>

</enunciate>`
This is the error log that is created:

> [ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.11.1:assemble (assemble) on project documentation: Error invoking Enunciate.: java.lang.StackOverflowError -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.11.1:assemble (assemble) on project documentation: Error invoking Enunciate.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error invoking Enunciate.
    at com.webcohesion.enunciate.mojo.ConfigMojo.execute (ConfigMojo.java:443)
    at com.webcohesion.enunciate.mojo.AssembleBaseMojo.execute (AssembleBaseMojo.java:102)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: java.lang.StackOverflowError
    at com.sun.tools.javac.main.Main.compile (Main.java:553)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall (JavacTaskImpl.java:129)
    at com.sun.tools.javac.api.JavacTaskImpl.call (JavacTaskImpl.java:138)
    at com.webcohesion.enunciate.Enunciate.run (Enunciate.java:674)
    at com.webcohesion.enunciate.mojo.ConfigMojo.execute (ConfigMojo.java:436)
    at com.webcohesion.enunciate.mojo.AssembleBaseMojo.execute (AssembleBaseMojo.java:102)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.StackOverflowError
    at java.lang.reflect.Proxy$Key1.<init> (Proxy.java:440)
    at java.lang.reflect.Proxy$KeyFactory.apply (Proxy.java:545)
    at java.lang.reflect.Proxy$KeyFactory.apply (Proxy.java:539)
    at java.lang.reflect.WeakCache.get (WeakCache.java:120)
    at java.lang.reflect.Proxy.getProxyClass0 (Proxy.java:419)
    at java.lang.reflect.Proxy.newProxyInstance (Proxy.java:719)
    at sun.reflect.annotation.AnnotationParser$1.run (AnnotationParser.java:305)
    at sun.reflect.annotation.AnnotationParser$1.run (AnnotationParser.java:303)
    at java.security.AccessController.doPrivileged (Native Method)
    at sun.reflect.annotation.AnnotationParser.annotationForMap (AnnotationParser.java:303)
    at com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation (AnnotationProxyMaker.java:87)
    at com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation (AnnotationProxyMaker.java:79)
    at com.sun.tools.javac.code.AnnoConstruct.getAnnotation (AnnoConstruct.java:179)
    at com.webcohesion.enunciate.javac.decorations.element.DecoratedElement.getAnnotation (DecoratedElement.java:293)
    at com.webcohesion.enunciate.javac.decorations.element.DecoratedTypeElement.getAnnotation (DecoratedTypeElement.java:145)
    at com.webcohesion.enunciate.modules.jaxb.model.util.JAXBUtil.findAdapterType (JAXBUtil.java:148)
    at com.webcohesion.enunciate.modules.jaxb.model.util.JAXBUtil.findAdapterType (JAXBUtil.java:134)
    at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration (MapType.java:150)
    at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration (MapType.java:152)
    at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration (MapType.java:152)
    at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration (MapType.java:152)
    at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration (MapType.java:152)
    at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration (MapType.java:152)

Any help would be appreciated.

**Comment by stoicflame** [comment]
Okay, thanks for the report.

**Comment by stoicflame** [comment]
It looks like there's something else specific to your use case that I can't seem to reproduce.

Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample). It seems to work for me. If you can modify it in a way that exposes the problem, I'd be happy to re-open this issue.

```diff
diff --git a/src/main/java/com/ifyouwannabecool/domain/persona/TypeA.java b/src/main/java/com/ifyouwannabecool/domain/persona/TypeA.java
index b170af9..d2449cb 100644
--- a/src/main/java/com/ifyouwannabecool/domain/persona/TypeA.java
+++ b/src/main/java/com/ifyouwannabecool/domain/persona/TypeA.java
@@ -3,5 +3,10 @@
  */
 package com.ifyouwannabecool.domain.persona;
 
-public class TypeA {
+import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
+
+import com.ifyouwannabecool.impl.TypeAXMLAdapter;
+
+@XmlJavaTypeAdapter(TypeAXMLAdapter.class)
+public class TypeA implements TypeB {
 }
diff --git a/src/main/java/com/ifyouwannabecool/impl/TypeAXMLAdapter.java b/src/main/java/com/ifyouwannabecool/impl/TypeAXMLAdapter.java
index 934515c..2d2ec08 100644
--- a/src/main/java/com/ifyouwannabecool/impl/TypeAXMLAdapter.java
+++ b/src/main/java/com/ifyouwannabecool/impl/TypeAXMLAdapter.java
@@ -3,5 +3,20 @@
  */
 package com.ifyouwannabecool.impl;
 
-public class TypeAXMLAdapter {
+import javax.xml.bind.annotation.adapters.XmlAdapter;
+
+import com.ifyouwannabecool.domain.persona.TypeA;
+import com.ifyouwannabecool.domain.persona.TypeB;
+
+public class TypeAXMLAdapter extends XmlAdapter<TypeA, TypeB> {
+
+  @Override
+  public TypeB unmarshal(TypeA v) throws Exception {
+    return null;
+  }
+
+  @Override
+  public TypeA marshal(TypeB v) throws Exception {
+    return null;
+  }
 }
```

**Comment by stoicflame** [comment]
Never mind on my last comment; I'm able to reproduce.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.

**Comment by GHFisher** [comment]
Hi, 
It is a great project.
I have the same issue below.
version: 2.18.0

Class AbstractObject:

@XmlJavaTypeAdapter(ImplementBean.ImplementXmlAdapter.class)
public abstract class AbstractObject {
...
}

Class ImplementBean:

public class ImplementBean extends AbstractObject {

...

	public static class ImplementXmlAdapter extends
	        XmlAdapter<ImplementBean, AbstractObject> {

	    @Override
	    public AbstractObject unmarshal(ImplementBean v) throws Exception {
	        return v;
	    }

	    @Override
	    public ImplementBean marshal(AbstractObject v) throws Exception {
	        return v == null ? null : new ImplementBean(v);
	    }
	}

}

Error stackoverflow:

	at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration(MapType.java:159)
	at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration(MapType.java:152)
	at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration(MapType.java:159)
	at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration(MapType.java:152)
	at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration(MapType.java:159)
	at com.webcohesion.enunciate.modules.jaxb.model.util.MapType.findMapTypeDeclaration(MapType.java:152)

**Comment by stoicflame** [comment]
Hello @GHFisher thanks for the report. Can you confirm you're on the latest version of Enunciate? If so, please open a new issue?

**Comment by GHFisher** [comment]
Yes. I am on 2.18.0. I will open a new issue for it
