### ISSUE TITLE
EnunciateException: <classname> is not recognized as a JSON type

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#96]
The error:

```
[WARNING] [ENUNCIATE] Enunciate support for Jackson 1.x is deprecated. It is recommended that you update to Jackson 2.x.
Jul 22, 2015 9:31:54 AM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
An error has occurred when reading existing sub-variable "body"; see cause
exception! The type of the containing value was: extended_hash+string
(com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl wrapped
into f.e.b.StringModel)
----
FTL stack trace ("~" means nesting-related):
- Failed at: ${type.example.body?xhtml} [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "processDataType" at line 948, column 58]
~ Reached through: #nested [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "boilerplate" at line 118, column 9]
~ Reached through: @boilerplate title=(title + ": " + ty... [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "processDataType" at line 842, column 5]
- Reached through: @file name=(type.slug + ".html") [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "processDataType" at line 841, column 3]
- Reached through: @processDataType type=type [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "processDataSyntax" at line 826, column 13]
~ Reached through: #nested [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "boilerplate" at line 118, column 9]
~ Reached through: @boilerplate title=(title + ": " + sy... [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "processDataSyntax" at line 807, column 5]
- Reached through: @file name=(syntax.slug + ".html") [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "processDataSyntax" at line 806, column 3]
- Reached through: @processDataSyntax syntax=syntax [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
at line 260, column 9]
~ Reached through: #nested [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
in macro "boilerplate" at line 118, column 9]
~ Reached through: @boilerplate pagenav=pagenav [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
at line 169, column 3]
- Reached through: @file name=indexPageName [in template
"jar:file:/C:/Users/kenib/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt"
at line 158, column 1]
----
Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
at freemarker.core.Dot._eval(Dot.java:40)
at freemarker.core.Expression.eval(Expression.java:78)
at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
at freemarker.core.BuiltInForString._eval(BuiltInForString.java:26)
at freemarker.core.Expression.eval(Expression.java:78)
at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
at freemarker.core.DollarVariable.accept(DollarVariable.java:40)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Macro$Context.runMacro(Macro.java:178)
at freemarker.core.Environment.invoke(Environment.java:700)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
at freemarker.core.Environment.visit(Environment.java:312)
at
freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
at
org.codehaus.enunciate.modules.docs.FileDirective.execute(FileDirective.java:48)
at freemarker.core.Environment.visit(Environment.java:377)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Macro$Context.runMacro(Macro.java:178)
at freemarker.core.Environment.invoke(Environment.java:700)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Macro$Context.runMacro(Macro.java:178)
at freemarker.core.Environment.invoke(Environment.java:700)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
at freemarker.core.Environment.visit(Environment.java:312)
at
freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
at
org.codehaus.enunciate.modules.docs.FileDirective.execute(FileDirective.java:48)
at freemarker.core.Environment.visit(Environment.java:377)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Macro$Context.runMacro(Macro.java:178)
at freemarker.core.Environment.invoke(Environment.java:700)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Macro$Context.runMacro(Macro.java:178)
at freemarker.core.Environment.invoke(Environment.java:700)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at
freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
at
org.codehaus.enunciate.modules.docs.FileDirective.execute(FileDirective.java:48)
at freemarker.core.Environment.visit(Environment.java:377)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.MixedContent.accept(MixedContent.java:62)
at freemarker.core.Environment.visit(Environment.java:312)
at freemarker.core.Environment.process(Environment.java:290)
at freemarker.template.Template.process(Template.java:312)
at
org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.processTemplate(DocumentationDeploymentModule.java:391)
at
org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.call(DocumentationDeploymentModule.java:344)
at
com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
at
com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
at
rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
at
rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
at
rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
at
rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
at
rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
at
rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
at
rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
at
rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
at
rx.subjects.SubjectSubscriptionManager$SubjectObserver.onCompleted(SubjectSubscriptionManager.java:232)
at rx.subjects.ReplaySubject.onCompleted(ReplaySubject.java:404)
at rx.Observable$35.onCompleted(Observable.java:7458)
at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:81)
at
rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
at
rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
at
rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
at
rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
at
rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
at
rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
at
rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
at
rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
at
rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
at
rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
at
rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
at
rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
at
freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
... 136 more
Caused by: com.webcohesion.enunciate.EnunciateException:
com.vce.vision.mvb.compliance.model.ComplianceProfileRule is not recognized
as a JSON type.
at
com.webcohesion.enunciate.modules.jackson1.model.types.JsonTypeVisitor.defaultAction(JsonTypeVisitor.java:45)
at
com.webcohesion.enunciate.modules.jackson1.model.types.JsonTypeVisitor.defaultAction(JsonTypeVisitor.java:41)
at
javax.lang.model.util.SimpleTypeVisitor6.visitDeclared(SimpleTypeVisitor6.java:157)
at
com.webcohesion.enunciate.modules.jackson1.model.types.JsonTypeVisitor.visitDeclared(JsonTypeVisitor.java:130)
at
com.webcohesion.enunciate.modules.jackson1.model.types.JsonTypeVisitor.visitDeclared(JsonTypeVisitor.java:41)
at
com.webcohesion.enunciate.javac.decorations.type.DecoratedDeclaredType.accept(DecoratedDeclaredType.java:83)
at
com.webcohesion.enunciate.modules.jackson1.model.types.JsonTypeFactory.getJsonType(JsonTypeFactory.java:157)
at
com.webcohesion.enunciate.modules.jackson1.model.Accessor.getJsonType(Accessor.java:129)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:59)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:96)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:72)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:96)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:128)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:72)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:96)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:72)
at
com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.getBody(ExampleImpl.java:42)
```

The class:

```java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complianceProfileRule", propOrder = {"title", "description", "selected", "complianceProfileValues", "checked"})
public class ComplianceProfileRule
{

    protected String                  title;
    protected String                  description;
    @XmlElement(defaultValue = "false")
    protected Boolean                 selected;
    protected ComplianceProfileValues complianceProfileValues;
    @XmlAttribute(required = true)
    protected String                  id;
    @XmlElement(defaultValue = "false")
    protected Boolean                 checked = false;
```

The reference to the class:

```java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complianceProfileRules", propOrder = {"complianceProfileRule"})
@XmlSeeAlso(value = {ComplianceProfileRule.class})
public class ComplianceProfileRules
{

    protected List<ComplianceProfileRule> complianceProfileRule;
```

**Comment by kandrelczyk** [comment]
I'm trying to upgrade to 2.0.0-M.1 and I'm getting this error. Is there a workaround?

**Comment by stoicflame** [comment]
[Milestone 2](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.2) is now available and should include the fix.
