### ISSUE TITLE
EnunciateReflectionsScanner tries to instantiate non-class files

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#973]
I just happened to enable debugging to find a problem with enuncate in a project.

There was a lot of noise in the output like the below.

Seems to me like the scanner should only try to instantiate files that are named *.class.

This is with enunciate 2.11.1.

````
15:23:36.997 [DEBUG] [org.reflections.Reflections] could not scan file META-INF/MANIFEST.MF in url file:/C:/udvikler/ws/.gradle_user_home/caches/modules-2/files-2.1/commons-codec/commons-codec/1.10/4b95f4897fa13f2cd904aee711aeafc0c5295cd8/commons-codec-1.10.jar with scanner EnunciateReflectionsScanner
org.reflections.ReflectionsException: could not create class object from file META-INF/MANIFEST.MF
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
	at com.webcohesion.enunciate.EnunciateReflectionsScanner.scan(EnunciateReflectionsScanner.java:91)
	at org.reflections.Reflections.scan(Reflections.java:253)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at com.webcohesion.enunciate.Enunciate.loadApiReflections(Enunciate.java:814)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:565)
	at com.webcohesion.enunciate.gradle.EnunciateTask.configureAndInvokeEnunciate(EnunciateTask.java:211)
	at com.webcohesion.enunciate.gradle.EnunciateTask.run(EnunciateTask.java:171)
...
````

**Comment by stoicflame** [comment]
I agree, but I'm afraid I can't reproduce the problem. The `Reflections` tool by default only scans `.class` files. I've tried reproducing the problem in the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) app and I've verified that there's no attempt to create a class object from `MANIFEST.MF`. I have no idea how your project is in a state where that's attempted. Any ideas?

**Comment by jskovjyskebankdk** [comment]
Cheers for trying. I'll see if I can find time to reproduce with enunciate-sample, but it is not a high priority for me.
I think I will close it, and re-open, if I find a way to reproduce with the same project - and then reopen.

Thanks!

**Comment by balaramk1998** [comment]
please don't send all these messages..
