### ISSUE TITLE
mediaTypes failure

### ISSUE THREAD

**Issue by marstonstudio** [stoicflame/enunciate#98]
Running enunciate 2.0.0-M1 in a project with Maven, Jersey, and Jackson which previously works with enunciate 1.30.1, got an error with media types

```
[DEBUG] [ENUNCIATE] Added com.babelcentral.services.engine.contentmap.ContentMapDialog as a Jackson type definition.
[DEBUG] [ENUNCIATE] Element com.babelcentral.services.engine.contentmap.ContentMapDialog is NOT to be added as a JAXB data type because [application/vnd.englishcentral-v1+json] doesn't seem to include XML.
[DEBUG] [ENUNCIATE] target/bridge/documentation is NOT up-to-date because it doesn't exist.
[DEBUG] [ENUNCIATE] Default base to be used for documentation base.
[DEBUG] [ENUNCIATE] Extracting css/ to target/bridge/documentation/css.
[DEBUG] [ENUNCIATE] Extracting css/style.css to target/bridge/documentation/css/style.css.
[DEBUG] [ENUNCIATE] Processing template jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt.
Jul 22, 2015 7:10:04 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
An error has occurred when reading existing sub-variable "mediaTypes"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jaxrs.api.impl.RequestEntityImpl wrapped into f.e.b.StringModel)

```

We are using custom media types in our Jersey API code to support versioning with accept headers. Sample code looks like
```
    @GET
    @Path("/{accountID}")
    @Produces({"application/vnd.englishcentral-v1+json"})
    @TypeHint(Account.class)
    public Response getV1(
            @Context HttpServletRequest hsr,
            @PathParam("accountID") final int accountID,
            @QueryParam("includeInactive") @DefaultValue("false") final boolean includeInactive,
            @QueryParam("fields") @DefaultValue(AccountFactory.DEFAULT_ACCOUNT_FIELDS) final String fields
    ) {

        return new AuthenticatedServiceAPI<Account>(hsr, ROLE_STUDENT | ROLE_TEACHER | ROLE_SERVER) {
            @Override
            public Account body(Visitor visitor) throws Exception {
                return AccountFactory.get(visitor, accountID, includeInactive, getFields(fields));
            }
        }.run();
    }
```

**Comment by marstonstudio** [comment]
Full stack trace

```
FTL stack trace ("~" means nesting-related):
	- Failed at: #list method.requestEntity.mediaTypes...  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 548, column 13]
	~ Reached through: #nested  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 118, column 9]
	~ Reached through: @boilerplate title=(title + ": " + re...  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 465, column 5]
	- Reached through: @file name=(resourceGroup.slug + ".ht...  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 464, column 3]
	- Reached through: @processResourceGroup resourceGroup=r...  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at line 195, column 11]
	~ Reached through: #nested  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 118, column 9]
	~ Reached through: @boilerplate pagenav=pagenav  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at line 169, column 3]
	- Reached through: @file name=indexPageName  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.0.0-M.1/enunciate-docs-2.0.0-M.1.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at line 158, column 1]
----
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
	at freemarker.core.Dot._eval(Dot.java:40)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:58)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
	at freemarker.core.Environment.invoke(Environment.java:700)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
	at org.codehaus.enunciate.modules.docs.FileDirective.execute(FileDirective.java:48)
	at freemarker.core.Environment.visit(Environment.java:377)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
	at freemarker.core.Environment.invoke(Environment.java:700)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
	at freemarker.core.Environment.invoke(Environment.java:700)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
	at org.codehaus.enunciate.modules.docs.FileDirective.execute(FileDirective.java:48)
	at freemarker.core.Environment.visit(Environment.java:377)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment.process(Environment.java:290)
	at freemarker.template.Template.process(Template.java:312)
	at org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.processTemplate(DocumentationDeploymentModule.java:391)
	at org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.call(DocumentationDeploymentModule.java:344)
	... 32 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
	... 114 more
Caused by: java.lang.ClassCastException: com.sun.tools.javac.code.Type$ClassType cannot be cast to com.webcohesion.enunciate.javac.decorations.type.DecoratedTypeMirror
	at com.webcohesion.enunciate.modules.jaxrs.api.impl.RequestEntityImpl.getMediaTypes(RequestEntityImpl.java:37)
	... 121 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:101)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:81)
	... 29 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by stoicflame** [comment]
Yes, this is another incarnation of the same root cause as #97.

We use media types the same way for the purposes of versioning.

Thanks again for the report.
